### ISSUE TITLE
Help configure React Starter Kit

### ISSUE THREAD

**Issue by duzenko** [firefox-devtools/vscode-firefox-debug#102]
My company is starting a new project based off React Starter Kit and I can't get it to debug in Firefox.
To reproduce this you'd need to clone from https://github.com/kriasoft/react-starter-kit and add a VSCode debug configuration. Here's my .vscode\launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}"
        },
        {
            "name": "Launch localhost",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}"
        },
    ]
}
```
Then I set a breakpoint in the render function (src\routes\home\Home.js) and press F5.
The chrome debugger works just fine - the breakpoint gets hit and VSCode stops. But the FF debugger for some reason does not work. The debugging session starts, a browser instance gets started, but the breakpoint does not get hit.
What am I missing here?
FWIW I enabled "Enable add-on debugging" and my FF version is 66.0.2 (64 bit)

**Comment by hbenl** [comment]
You'll need to add `pathMappings` to tell this adapter how to map the urls to file paths. This is what worked for me (you'll have to replace `<absolute-path-to-your-workspace>`):
```
"pathMappings": [
	{
		"url": "http://localhost:3000/<absolute-path-to-your-workspace>/src/",
		"path": "${workspaceFolder}/src/"
	}
]
```
You can easily create `pathMappings` yourself by using the context menu in the Loaded Scripts Explorer:
![Screenshot_2019-04-04_22-10-05](https://user-images.githubusercontent.com/16060807/55585545-33729880-5727-11e9-93fd-43464254ba54.png)

Note that the urls contain the absolute path of your workspace, which means this configuration breaks when you move the folder (and it probably won't work on other people's machines since the absolute path usually contains the username).
As a hack you can try this configuration which should be portable:
```
"pathMappings": [
	{
		"url": "http://localhost:3000/",
		"path": ""
	}
]
```
(Note that these `pathMappings` would break every non-React project out there)
I'll have a look at the Chrome adapter to see how they create default `pathMappings` for projects that do this put-the-absolute-project-path-in-the-url stuff.

**Comment by duzenko** [comment]
Sorry, neither worked for me. The breakpoint in Home.js just does not get hit.
Here's my launch.json - please advise

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}"
        },
        {
            "name": "firefox 1",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "url": "http://localhost:3000/",
            "webRoot": "${workspaceFolder}",
            "pathMappings": [
                {
                    "url": "http://localhost:3000/d:/temp/react-starter-kit-master/src/",
                    "path": "${workspaceFolder}/src/"
                }
            ]
        },    
        {
            "name": "firefox 2",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "url": "http://localhost:3000/",
            "webRoot": "${workspaceFolder}",
            "pathMappings": [
                {
                    "url": "http://localhost:3000/",
                    "path": ""
                }
            ]
        },
    ]
}
```

**Comment by hbenl** [comment]
I tried on Windows now and it works for me _even without `pathMappings`_.
I had to hit the reload button in Firefox though, that's a known weakness (which is also mentioned in the documentation): breakpoints sometimes don't get hit when a file is run for the first time.
When you start the debugger, does the breakpoint remain grey or does it turn red again eventually?
You'll find the Loaded Scripts Explorer in the Debug side bar, usually below the Breakpoints view.

**Comment by hbenl** [comment]
Also, Firefox got stuck in my Windows VM once: it seemed to never finish loading the page. I had to close the Firefox window and try again, after that it worked.

**Comment by Fubuchi** [comment]
@hbenl my breakpoints are all grey and the loaded scripts explorer only had the `webpack://` , my config is same as OP.

**Comment by duzenko** [comment]
Right, F5 in FF after initial load worked for me. 
Thanks a lot.

**Comment by synchronos-t** [comment]
Unfortunately, refreshing the page in Firefox doesn't work for me. All the breakpoints stay as gray circles. The path mappings are definitely correct. I believe they work even without pathMappings, but I've also tried by setting them through the Loaded Scripts tab, to no avail. Otherwise the debugger works; at least I get all the browser console lines into the VSCode console. The breakpoints also work in Firefox itself; just not in VSCode.

I use Create React App with react-scripts 2.1.8. Its Webpack seems to already create source mappings into actual absolute directories, and in both Firefox Debugger tab and VSCode Loaded Scripts I see those. E.g. `c:/Users/[my user id]/OneDrive/[some more directories...]/react-ui/src/App.js`. And those are correct. Furthermore, they show in the PathConversion log as successful, e.g. `PathConversion: Sourcemapped absolute path: c:/Users/[my user id]/OneDrive/[some more directories...]/react-ui/src/components/form/TimeTextField.js`. Still, the breakpoints don't get enabled in Firefox.

So, I'm quite out of options how to debug this problem any more.

**Comment by hbenl** [comment]
@Fubuchi it'd be interesting to see what shows up when you expand the `webpack://` entry in the Loaded Scripts Explorer for Firefox. Furthermore, your webpack config and a diagnostic log from the debugadapter (with the `PathConversion` and `SourceMappingThreadActorProxy` loggers set to `Debug`) could be helpful to diagnose the problem.

@synchronos-t please set the `SourceMappingThreadActorProxy` logger to `Debug` (it will show messages about the sourcemapping done when it tries to set breakpoints) and then post those messages for one breakpoint that you're trying to set and the corresponding message from the `PathConversion` logger for that file.

**Comment by synchronos-t** [comment]
OK, I found the culprit. Should have spotted it earlier. It was the space craracter in the directory name. The source maps are URL encoded, naturally, so that the browser can handle them, but the Windows file system doesn't. Perhaps the source mapper should made to URL decode the paths?

**Comment by Fubuchi** [comment]
Here is the screen shot of expanded `webpack://` :

![image](https://user-images.githubusercontent.com/42483897/55975038-464f1500-5cb3-11e9-80be-0564b8435a07.png)

Here is my webpack config: 
[webpack.config.js.zip](https://github.com/hbenl/vscode-firefox-debug/files/3069704/webpack.config.js.zip)

Here is the log file after I started debug with 2 pre-set breakpoints: 
[log.log](https://github.com/hbenl/vscode-firefox-debug/files/3069720/log.log)


I've just found some interested thing: If I set another break point after I started debug, ALL break points will turn red and work after a delay of about 5s (no reload require but just reload without set new break point do not work).

Here is the log after I add another break point:
[log.log](https://github.com/hbenl/vscode-firefox-debug/files/3069731/log.log)

**Comment by Fubuchi** [comment]
Here is the screen shot of expanded `webpack://` :

![image](https://user-images.githubusercontent.com/42483897/55975038-464f1500-5cb3-11e9-80be-0564b8435a07.png)

Here is my webpack config: 
[webpack.config.js.zip](https://github.com/hbenl/vscode-firefox-debug/files/3069704/webpack.config.js.zip)

Here is the log file after I started debug with 2 pre-set breakpoints: 
[log.log](https://github.com/hbenl/vscode-firefox-debug/files/3069720/log.log)


I've just found some interested thing: If I set another break point after I started debug, ALL break points will turn red and work after a delay of about 5s (no reload require but just reload without set new break point do not work).

Here is the log after I add another break point:
[log.log](https://github.com/hbenl/vscode-firefox-debug/files/3069731/log.log)

**Comment by hbenl** [comment]
I found 2 bugs: 
* one of them is in `create-react-app`, it generates sourcemaps that contain paths where there should be urls (at least that's what the spec says - but who cares about specs on the web...) - I have added a workaround for this
* the other was in the handling of paths on Windows when setting breakpoints: the drive letters I get from VS Code and from Webpack are sometimes uppercase and sometimes lowercase and my code didn't handle this correctly - this is fixed now

I have published version 1.7.11, please test it and tell me if it works for you.

P.S.
> Perhaps the source mapper should made to URL decode the paths?

Absolutely, and it usually does. But the paths-instead-of-urls issue got my code so confused that it didn't decode in this case.

> I've just found some interested thing: If I set another break point after I started debug, ALL break points will turn red

That observation saved me soooo much time when looking for the bug :)

**Comment by hbenl** [comment]
@Fubuchi I saw that you use `devtool: 'source-map'` in your webpack config. If it still doesn't work with version 1.7.11, you may want to try other options here - in my experience, only the `*-eval-*` values for the `devtool` option are reliable (see also webpack/webpack#5491).

**Comment by rugk** [comment]
> one of them is in create-react-app

Did you possibly also reported it to `create-react-app`?

**Comment by Fubuchi** [comment]
@hbenl `*-evel-*` didn't work but `*-source-map` work 🤔

**Comment by hbenl** [comment]
@rugk facebook/create-react-app#6828

@Fubuchi Perhaps there's a misunderstanding here: I didn't mean to set `devtool` to `*-eval-*` literally, but to set it to any of the [allowed values](https://webpack.js.org/configuration/devtool/#devtool) that contain `-eval-`.

**Comment by Fubuchi** [comment]
@hbenl I try `eval` and it work, I'm just moved from backend dev to frontend so everything still new for me.

There is some magic now, after try some of values containing `eval` in webpack's document and they work, I try set it back to `source-map` and it work too!

**Comment by digitarald** [comment]
Closing, as the last comment suggests this works.

If anybody else runs into this issue, https://github.com/firefox-devtools/vscode-firefox-debug/issues/102#issuecomment-483040204 has pointers to the fixing source maps settings.
