### ISSUE TITLE
No more working since v1.8.1 under linux

### ISSUE THREAD

**Issue by stephanedr** [firefox-devtools/vscode-firefox-debug#111]
Up to version 1.8.0, I was able to debug, though I had to start the debugger twice.

Linux: Solus
Firefox: 68.0 - all other extensions disabled (so only Firefox debugger enabled)

Reporting the behavior of the few last versions:

**1.7.11**
* Start debugger: Firefox opens (1 firefox process created), but the debugger doesn't work.
* Stop debugger: Firefox doesn't close.
* Start debugger (with the previous Firefox still open): a 2nd Firefox window opens, the debugger doesn't work from this 2nd window, but is working from the 1st window.
* Stop debugger: the 2nd window closes, the 1st doesn't close.

**1.8.0**
* Start debugger: no Firefox window opens. 2 firefox processes created, one being zombie.
* Stop debugger: Firefox window opens (from the non-zombie process). The zombie process has disappeared.
* Start debugger (with the previous Firefox still open): no 2nd window opens. 2 additional firefox processes created, one being zombie. The debugger is working (so from the 1st process).
* Stop debugger: the 2 processes created from the 2nd start have disappeared. The window doesn't close.

**1.8.1, 1.8.2**
* Start debugger: no Firefox window opens. 2 firefox processes created, one being zombie.
* Stop debugger: the 2 processes have disappeared.
* Restarting the debugger recreates 2 processes (so without a window).

**Comment by hbenl** [comment]
This should be fixed in version 1.8.3, which I just released.
I noticed that Firefox is slow to start up in Solus, so I increased the initial timeout to 10 seconds. If that is still not enough and you get an error saying "connect ECONNREFUSED 127.0.0.1:6000", please report it here and I will make that timeout configurable.

**Comment by stephanedr** [comment]
Thanks for the fix. I won't be able to test it before Thursday. I'll keep you informed.
I indeed sometimes have this timeout error, but only if Firefox was not launched before the first debug.

**Comment by stephanedr** [comment]
I tested and the debugger is working fine (no more need to launch the debugger twice). Thanks.
I still get the ECONNREFUSED message if I launch the debugger without having launched Firefox before. Maybe you can add this configurable, but it's not a big issue for me.

There is still one difference compared to the behavior under Windows: when starting the debugger, Firefox does not get the focus (the focus stays on VSCode). I don't know whether it's complex to improve this. Do you prefer I create another issue?

**Comment by hbenl** [comment]
OK, so I'll make the initial timeout configurable.
I don't know if and how I can influence the focusing behavior. Anyway I'd say this should be left to the platform's window manager to decide.

**Comment by hbenl** [comment]
I have added the `timeout` configuration property in version 2.1.0 (but forgot to add it to the README before publishing). Set it to the timeout in seconds for the adapter to connect to Firefox after launching it.

**Comment by stephanedr** [comment]
Thanks.
