### ISSUE TITLE
Update to and new Firefox Browser design

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/vscode-firefox-debug#113]
@digitarald wrote:

> I saw other extensions use 256px, which looks more crisp on HDPI screens – especially as marketplace.visualstudio.com is already using the icon in 128px.

On top of that, maybe we could use the new Firefox Browser icon, which landed in Nightly (purple variant) and might land in Beta (with standard color) in a couple weeks?

**Comment by hbenl** [comment]
I've updated the icon to 256px and will switch to the new icon when the stable Firefox release makes the switch.

**Comment by digitarald** [comment]
Now that 70 is out with the new logo, we need to get this done.

**Comment by hbenl** [comment]
@digitarald Yeah, I've got it planned for the next release, which I hope to get done by the end of the week.
