### ISSUE TITLE
Package firefoxDebugAdapter as a standalone npm module 

### ISSUE THREAD

**Issue by AObuchow** [firefox-devtools/vscode-firefox-debug#114]
Hello, I am currently working on integrating the Firefox debugger into Eclipse using this project's debug adapter. [Here's an early demonstration of it working in Eclipse. ](https://youtu.be/-4Uh1Flhf1Q)

Would it be possible to publish the debug adapter (firefoxDebugAdapter.js) on npmjs? 
This would greatly benefit all IDE's wanting to integrate Firefox's debuger.

**Comment by hbenl** [comment]
Awesome!
I am currently trying to create a `webpack` bundle for the adapter - I think that could be an even easier option for integration into other IDEs: instead of shipping all of the adapter's javascript files plus the `node_modules` folder with all of the adapter's dependencies, you'd only have to ship 3 files (the bundle, the `.wasm` file from the `source-map` npm package and another script that is run in a child process). Do you think that option would work for you or would you still prefer an npm package?

**Comment by hbenl** [comment]
> where would those 3 files (bundle, wasm and the script) be published?

Well, you could just copy them from the extension that is published on the VS Code Marketplace, but I could also publish them as an npm package.

**Comment by mickaelistria** [comment]
In Eclipse Wild Web Developer, wealready deal with npm for other services and are already using it to provision the dEbug adapter. See pom.xml in https://github.com/eclipse/wildwebdeveloper/commit/b1f39b6daa79e4848cf1fd3b287c9de0b7b56469 for details.
So at the moment, npm package on npmjs would be best for us. Web assembly would actually add complexity here, without added value.

**Comment by hbenl** [comment]
OK, I've published the debug adapter on npm as `firefox-debugadapter`.
It's the bundled version and it also contains the webassembly (which is necessary for the adapter to work), but that shouldn't make any noticeable difference for you (except that the bundled version is much smaller and faster to load).

**Comment by mickaelistria** [comment]
Thank you very much!

**Comment by AObuchow** [comment]
Awesome, thank you !!

**Comment by mickaelistria** [comment]
npm package adopted in Wild Web Developer.

**Comment by digitarald** [comment]
@mickaelistria let me know if Firefox DevTools can help in any way to better integrate with Eclipse. Happy to collaborate on outreach as well.

**Comment by AObuchow** [comment]
[Another demo of the Firefox debugger working in Eclipse](https://youtu.be/4Q_-CtvsEjY). 
Reload on change is pretty awesome :)

**Comment by rugk** [comment]
Sry, did I miss something or what does this have to do with vscode-firefox-debug?

**Comment by AObuchow** [comment]
> Sry, did I miss something or what does Eclipse have to do with vscode-firefox-debug?

firefoxDebugAdapter.js (from vscode-firefox-debug) is being used to integrate Firefox's debugger into Eclipse. My last comment was just an update on the integration progress.
