### ISSUE TITLE
[Debug Adapter] `this` added as many times as `variables` is invoked

### ISSUE THREAD

**Issue by mickaelistria** [firefox-devtools/vscode-firefox-debug#115]
If I'm invoking `variables` N times from the same breakpoint, then `this` is added one more time by invocation.

See screenshot of the result in Eclipse IDE.
![Screenshot from 2019-08-28 10-53-57](https://user-images.githubusercontent.com/469058/63841019-4f026800-c982-11e9-81f5-f5bf9f2c708b.png)

**Comment by hbenl** [comment]
Thanks, I've fixed this in the version that I just published on npm.
