### ISSUE TITLE
Disbale firefox telemetry

### ISSUE THREAD

**Issue by RsPlayer** [firefox-devtools/vscode-firefox-debug#119]
I want to debug firefox without telemetry, can you add `"telemetry": false` in your debug options? or is it not possible? I can't keep disabling it everytime

**Comment by RsPlayer** [comment]
> @RsPlayer do you want to disable telemetry collection in Firefox or in VS Code?
> 
> In case of Firefox, you could use `profile`/`profileDir` to retain any preference changes and then opt out of data collection in [Firefox's preferences](https://support.mozilla.org/en-US/kb/share-data-mozilla-help-improve-firefox).

I want to disbale it when I start debugging for firefox. because when I start debugging it always show me a notification saying that telemetry is enabled which it is annoying

**Comment by digitarald** [comment]
@RsPlayer re-using the same profile with the `profile` pref should help there. I will follow up on the Firefox side to make this more seamless.

**Comment by RsPlayer** [comment]
It works!
I created new profile, changed settings and then added `"profile": "Debugger"`

Thank you

**Comment by hbenl** [comment]
I just found (with @digitarald's help) another solution: if you add
```
"preferences": {
    "datareporting.policy.dataSubmissionPolicyBypassNotification": true
}
```
to your `launch.json`, then the prompt won't show up, even when you use temporary profiles.

**Comment by RsPlayer** [comment]
Instead of bypassing notifications, I can also disbale telemetry like this
```
"preferences": {
        "toolkit.telemetry.unfied": false,
}
```
source: https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/internals/preferences.html#id1

notification never appear again, but telemetry it still enabled in preferences idk why.
Anyways, problem is solved. thank you for help.

**Comment by RsPlayer** [comment]
Update: It seems that @digitarald & Firefox updated their datareporting policy now.

No need for any additional preference anymore.
