### ISSUE TITLE
Breakpoint sources are not found after Webpack makes hot update

### ISSUE THREAD

**Issue by synchronos-t** [firefox-devtools/vscode-firefox-debug#134]
I have a problem where breakpoints don't find their source any more after Webpack makes hot update for the part of the code. I'm Using Create React App. I'm not sure if this is Webpack's HMR or not, because CRA always anyway refreshes the whole page.

However, the problem is that Webpack anyway doesn't compile everything into one bundle, unless I reboot the whole development server, and if the breakpoint is located inside the code which is in the hot update file, I only see an error on the call stack: Couldn't find source adapter for server1.conn7.child1/source455/!file:///C:/... (the path after this is indeed the correct one).

I put the "PathConversion": "Debug" and "SourceMappingThreadActorProxy": "Debug" inside the launch.json, which produces me these two lines (the ones I believe are the relevant ones):

DEBUG|385.702|SourceMappingThreadActorProxy: Trying to sourcemap {"actor":"server1.conn7.child1/source455","extensionName":null,"url":"http://localhost:3000/static/js/main.chunk.js","isBlackBoxed":false,"sourceMapURL":"main.chunk.js.map","introductionUrl":null,"introductionType":"scriptElement"}

DEBUG|385.815|SourceMappingThreadActorProxy: Trying to sourcemap {"actor":"server1.conn7.child1/source456","extensionName":null,"url":"http://localhost:3000/main.af6f080d41afe0531da6.hot-update.js","isBlackBoxed":false,"sourceMapURL":"main.af6f080d41afe0531da6.hot-update.js.map","introductionUrl":null,"introductionType":"scriptElement"}

Please note that the main source chunk is the source455 and the hot patched bit is source456.

Is there something I could do for it to work with putting some sourcemapping?

**Comment by hbenl** [comment]
I couldn't reproduce this but I have a theory about what could cause this. If my theory is correct then this should only happen when the breakpoint is hit _immediately_ after the hot update, but not if the breakpoint is hit later (e.g. if it is in a callback that is triggered by some user interaction). Could you please check if this is the case in your project?

**Comment by synchronos-t** [comment]
Unfortunately no. It happens after multiple page reloads and debugger restarts. Somehow when I now tested, I got some breakpoints to work again after disconnecting and reconnecting. There isn't any clear pattern how they start work again. At one point some breakpoints unexpectedly got working when I added a new one to another file. At another point, new breakpoints didn't get added before I restarted the debugger. I also tried waiting for a couple of minutes without reconnecting or refreshing, but they didn't start working. At some point the call stack vanished and didn't come back with restarts, only after a disconnect and reconnect, after which some breakpoints stopped working completely. With a page reload and debugger restart they started again working, but without finding the source.

**Comment by hbenl** [comment]
Hmm, I think there are (at least) two problems that get mixed up here: breakpoints do not get hit after the hot update and breakpoints do get hit but an error message is shown instead of the stacktrace.
In the coming days I will fix the issues that I found and then we'll see if there are more.

**Comment by hbenl** [comment]
Please try with version 2.3.3 and tell me if there are remaining issues.

**Comment by synchronos-t** [comment]
Unfortunately now every time when I refresh the page when the debugger is on, Javascript execution stops. Doesn't show any breakpoint, the call stack says just "Running", but nothing happens. It continues execution after I disconnect the debugger.

**Comment by synchronos-t** [comment]
Also, when I do the disconnect after it hangs at reload, if I try to reconnect, the breakpoints don't work any more. I get everything working again if I restart the CRA development server, though, but that seems to be the only way.

**Comment by hbenl** [comment]
OK, I introduced a severe performance issue with my HMR fixes, sorry about that.
Version 2.3.4 should work a lot better (most of all it should not hang after a reload anymore), but I'm planning to rework how the adapter handles breakpoint positions with sourcemaps, the performance can still be improved.

**Comment by synchronos-t** [comment]
I haven't yet got time to test throroughly, but based on my preliminary tests the breakpoints work much better now. Thanks! I'll close this for now.
