### ISSUE TITLE
Feature request: load source map from local disk when it cannot be loaded from the server

### ISSUE THREAD

**Issue by stephanedr** [firefox-devtools/vscode-firefox-debug#136]
In server mode, if a source map cannot be loaded from the server, try to load it from the local disk.
The path of the source map should be determined from the local JS file.

**Comment by hbenl** [comment]
Actually I went a bit further: in version 2.4.0, the extension always tries to load sourcemaps from disk first (if the URL can be mapped to a local path). Only when that fails it will try to get it from the server.

**Comment by stephanedr** [comment]
Working fine. Thanks.
