### ISSUE TITLE
Please add support for `console.clear` to clear the console.

### ISSUE THREAD

**Issue by Umphs** [firefox-devtools/vscode-firefox-debug#139]
Calling console.clear, clears the console in most inspectors but the extension leaves this method useless.

I have a live reload of my code and the logs get really messy especially if I log something from a game loop.

Also, is it possible to have a flag to clear console on page reload, or is it not feasible ?

**Comment by hbenl** [comment]
@miggs125 Thanks for the offer, but I had already been working on it (see #142)

**Comment by hbenl** [comment]
I have added support for `console.clear()` and a new configuration property `clearConsoleOnReload` in version 2.4.0.

**Comment by Umphs** [comment]
Thanks for the implementation, I will use firefox as default debugging browser again.
