### ISSUE TITLE
normalize slashes in addonPath

### ISSUE THREAD

**Issue by carlin-q-scott** [firefox-devtools/vscode-firefox-debug#147]
About a year ago, this add-on stopped installing my Firefox WebExtension. Today I discovered the culprit in my log file:
> DEBUG|006.569|DebugConnection: Sending request {"to":"server1.conn0.addonsActor5","type":"installTemporaryAddon","addonPath":"C:\\Users\\Carlin\\Documents\\Projects\\BrowserMediaPlayers/dist/firefox"}
DEBUG|006.589|DebugConnection: Received response/event {"from":"server1.conn0.addonsActor5","error":"unknownError","message":"Could not install add-on at 'C:\\Users\\Carlin\\Documents\\Projects\\BrowserMediaPlayers/dist/firefox'

My `addonPath` is: `"${workspaceFolder}/dist/firefox"`.
If I switch it to Windows pathing, it works: `"${workspaceFolder}\\dist\\firefox"`

**Comment by hbenl** [comment]
Fixed in version 2.5.2. Thanks for the bugreport.
