### ISSUE TITLE
Breakpoints don't work in a CRA app

### ISSUE THREAD

**Issue by synchronos-t** [firefox-devtools/vscode-firefox-debug#162]
I'm using Create-React-App and debugging with attach. (VSCode 1.40.1.) The debugger has previously worked fine, and I don't think anything in my configuration has changed. The debugger attaches successfully and I see the console log. Also, seeing the log with `"PathConversion": "Debug"` and `"SourceMappingThreadActorProxy": "Debug"` I see that the source mapping works just fine, for instance:

`DEBUG|000.666|PathConversion: Converted url file:///C:/Users/***/***/src/components/TextBubble.js to path C:/Users/***/***/src/components/TextBubble.js`

However, the breakpoints stay as unverified. Reloading the browser page after launching the debugger doesn't help. Also restarting or disconnecting and reattaching the debugger doesn't help. Firefox's internal debugger successfully breaks in the same point.

If I use the `"default" = "Debug"` setting, I can get when I launch the debugger this line (for my two test breakpoints):
`DEBUG|000.166|BreakpointsManager: Setting 2 breakpoints for c:\Users\***\***\src\components\feed\CompleteNoAnswer.js`

I also get similar ones when I add new breakpoints or remove old ones. So, at least it tries to set the breakpoints, but I can't get any clue why it doesn't succeed.

One minor oddity I can spot is that in the line above the drive letter C is lowercase, when in other places it's in uppercase. It shouldn't matter in Windows file system, but don't know if it somehow matters when setting the breakpoint (e.g. if Firefox compares them case-sensitively to find the correct place to put it or something).

Any other guess I can make is that could it be related to these lines in the log:
`DEBUG|013.694|PathConversion: Converted url http://localhost:3000/app/feed/all to path C:/Users/***/***/app/feed/all`
`DEBUG|014.480|PathConversion: Converted url http://localhost:3000/static/js/main.chunk.js.map to path C:/Users/***/***/static/js/main.chunk.js.map`
Those seem a bit odd in the log, as I don't get why the debugger would try to path convert those addresses in the first place. But as I don't know the inner workings of the debugger, they might just as well be part of normal functioning.

Also, the call stack doesn't show anything, if I have just one tab open in the browser. If I open a second tab and reattach, then I see two tabs in the status "running", but I don't see anything under either of them.

I haven't used the debugger for a while, so I can't say exactly when it's stopped working. Might be any point in the last, say, two months.

**Comment by hbenl** [comment]
Sorry, my bad: a fix for a Windows pathmapping bug introduced another Windows pathmapping bug...

FYI:
> One minor oddity I can spot is that in the line above the drive letter C is lowercase, when in other places it's in uppercase.

That's the problem: the paths need to match exactly and in this case they don't because of the drive letter casing _and_ because of `/` vs. `\`.

> Also, the call stack doesn't show anything

Well, it remains empty until you hit a breakpoint...

> I haven't used the debugger for a while, so I can't say exactly when it's stopped working.

It stopped working in version 2.5.2.

**Comment by hbenl** [comment]
Fixed in 2.5.3

**Comment by synchronos-t** [comment]
Great, it works now, thanks for the quick response!
