### ISSUE TITLE
add support for nightly

### ISSUE THREAD

**Issue by 9034725985** [firefox-devtools/vscode-firefox-debug#165]
I created an angular project based on the suggestions over at https://github.com/firefox-devtools/vscode-firefox-debug/issues/140#issuecomment-543808028  

The repo is at https://github.com/kusl/personal-website 
I added my launch json and tasks json at https://github.com/kusl/personal-website/commit/4deb593cd37ebcee96018b213680bf665be62706 

When I open Firefox Nightly, I get the following message: 

![Screenshot (5)](https://user-images.githubusercontent.com/1676445/69933205-21e6b980-148b-11ea-936f-6ff700b36cfb.png)

Nightly troubleshooting info: 

Name | Firefox
-- | --
Version | 72.0a1
Build ID | 20191201211801

Firefox does launch just fine though.

**Comment by hbenl** [comment]
Thanks for the bugreport. This is actually a bug in the feature detection logic, I'll fix this soon.

**Comment by kspdrgn** [comment]
Same issue with "developer edition", running version 72.0b1 64bit and the debug plugin complains for version "68 or later"

**Comment by ievgenk** [comment]
> Same issue with "developer edition", running version 72.0b1 64bit and the debug plugin complains for version "68 or later"

Experiencing exact same issue

**Comment by hbenl** [comment]
I fixed the version detection, but there seem to be some breaking changes in the debug protocol in Firefox 72, so it still won't work.
Please use the standard edition for now, I'll fix this soon.

**Comment by hbenl** [comment]
Fixed in version 2.5.5
