### ISSUE TITLE
Debugger unresponsive on WebExtension breakpoint

### ISSUE THREAD

**Issue by adalinesimonian** [firefox-devtools/vscode-firefox-debug#168]
### Environment

vscode 1.40.2
Firefox Developer 72.0b2
vscode-firefox-debug 2.5.4
Windows 10 build 1903

### Code

- extension/main.js

```js
alert('Extension loaded.')
let x = 5
x++ // Breakpoint set here
console.log(x)
```

- extension/manifest.json

```json
{

  "manifest_version": 2,
  "name": "Test Extension",
  "version": "0.1",

  "description": "Tests absolutely nothing important",

  "icons": {
    "48": "icons/border-48.png"
  },

  "content_scripts": [
    {
      "matches": [
        "*://*.example.com/*"
      ],
      "js": ["main.js"]
    }
  ]

}
```

- extension/.vscode/launch.json

```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "firefox",
        "request": "launch",
        "reAttach": true,
        "name": "Launch add-on",
        "addonPath": "${workspaceFolder}"
      }
    ]
}
```

### Expected behaviour

Debugger pauses on breakpoint at `x++` and debugging tools in vscode are functional.

### Actual behaviour

Debugger seems to pause on breakpoint at `x++`, however all the debugging tools in vscode are unresponsive and watch expressions don't work.

![Screenshot of Call Stack panel](https://user-images.githubusercontent.com/9868643/70165002-03451600-1677-11ea-8ee5-db98891abce3.png)

![Screenshot of Watch panel](https://user-images.githubusercontent.com/9868643/70165077-240d6b80-1677-11ea-99ea-9c77cfa2ff7f.png)

**Comment by hbenl** [comment]
There was an incompatibility with Firefox 72. It's fixed in version 2.5.5 of this extension.
