### ISSUE TITLE
command 'extension.firefox.xxx' not found

### ISSUE THREAD

**Issue by Wobblebase** [firefox-devtools/vscode-firefox-debug#170]
After installation of the addon all commands, like 'Firefox: reload add-on' show a error-message along the lines of "command 'extension.firefox.relaodAddon' not found".
The commands themselves show up in the command-palette normally.
I tried to uninstall and reinstall the addon and also visual studio code itself.

**Comment by hbenl** [comment]
The extension isn't started until you start your first Firefox debug session, I'm guessing that is why the commands can't be found. The commands need a running Firefox debug session anyway.
So try starting a Firefox debug session before calling any of the commands and tell me if that fixes the issue.

**Comment by Wobblebase** [comment]
I started a firefox debug session with -start-debugger-server, made sure that the following were set:
devtools.debugger.remote-enabled | true 
devtools.chrome.enabled | true 
devtools.debugger.prompt-connection | false.
Furthermore I confirmed that firefox is listening on port 6000, restarted visual studio code and still the same error message occurred.

**Comment by hbenl** [comment]
You need to start a [debug session in VS Code](https://code.visualstudio.com/docs/editor/debugging): create a `launch.json` file and click the "Start debugging" button so that it launches or attaches to Firefox.

**Comment by Wobblebase** [comment]
It works. Thank you very much.
