### ISSUE TITLE
Broken user.js in Firefox profile when using a custom profile with profile changes kept.

### ISSUE THREAD

**Issue by OkazakiNagisa** [firefox-devtools/vscode-firefox-debug#175]
in vscode settings:
...
"firefox.keepProfileChanges": true,
"firefox.profile": "test",
...

Steps to reproduce this bug:
Create a profile named test in Firefox.
Debug a website, then a normal user.js will be created in test profile folder.
Stop debugging, then start again.
Line 18 in user.js will be like this:
user_pref("startup.homepage_welcome_url", about:blank");
with a quotation mark missing.

My environment:
版本: 1.41.1
提交: 26076a4de974ead31f97692a0d32f90d735645c0
日期: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

名称: Debugger for Firefox
id: firefox-devtools.vscode-firefox-debug
说明: Debug your web application or browser extension in Firefox
版本: 2.6.1
发布者: Firefox DevTools
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=firefox-devtools.vscode-firefox-debug

**Comment by hbenl** [comment]
This is a bug in an upstream project for which I created a pull request. Once the PR is merged, I will update this extension.
Thanks for the bug report.

**Comment by hbenl** [comment]
Fixed in version 2.7.0.
