### ISSUE TITLE
Breakpoints aren't working with Next.js app

### ISSUE THREAD

**Issue by h-jennings** [firefox-devtools/vscode-firefox-debug#177]
## Issue
I am unable to get a breakpoints to work in a next.js application.

### Here's my current firefox configuration:

```json
{
    "type": "firefox",
    "request": "launch",
    "name": "Debugger:firefox",
    "url": "http://localhost:3000",
    "webRoot": "${workspaceFolder}",
    "skipFiles": [
      "node-modules/**"
    ],
    "clearConsoleOnReload": true,
  }
```

This properly launches a firefox instance against localhost, however, when I attempt to add a breakpoint in my editor, I end up seeing this popup in my editor:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/38039731/72455873-981c5280-3791-11ea-8084-6641ef330909.png">

**Selecting 'yes' for the path mapping wizard does nothing.**

### Here's my working chrome configuration for comparison:

```json
{
    "type": "chrome",
    "request": "launch",
    "name": "Launch Chrome against localhost",
    "url": "http://localhost:3000",
    "webRoot": "${workspaceFolder}",
    "sourceMaps": true,
    "smartStep": true,
    "skipFiles": [
      "node-modules/**",
      "interpreter.js"
    ]
  }
```

## Suggestion
This is a bare bones next.js app. Since next.js is becoming more of a popular React.js framework, it might be helpful to have an example in the documentation (provided that this extension is compatible).

**Comment by jasonwilliams** [comment]
Reproduction steps:
* VSCode (v1.41.1)
* Make sure you have the "Debugger for Firefox" (im using 2.6.1)
* Check out https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example @ 315318e21619f16f09e593b8b255e45de1a66a7b
* npm install
* Set breakpoint in index.tsx
* npm run-script dev

**Result**
Breakpoint doesn't fire

**Screenshot/Image**
![noBreakpoint](https://user-images.githubusercontent.com/936006/73477998-2a754680-438d-11ea-83bd-d9e0ddfbd699.gif)

**Potentially Related**
https://github.com/zeit/next.js/issues/9471
It may or may not be the same issue, Chromium doesn't show this warning.

@h-jennings could you confirm wether or not you have this error in your console?
![image](https://user-images.githubusercontent.com/936006/73476864-06b10100-438b-11ea-99f8-19e8964e9002.png)

**Comment by h-jennings** [comment]
@jasonwilliams Just fired up my dev server and do indeed have the same error message.
<img width="1284" alt="Screen Shot 2020-01-30 at 2 02 13 PM" src="https://user-images.githubusercontent.com/38039731/73481203-5252b300-4369-11ea-9f3f-3920eacbca88.png">

Still haven't been able to fix this issue. I'm just using the Chrome debugger in the meantime.

**Comment by jasonwilliams** [comment]
I think until Firefox can fix this using Chrome is the only option, I’m not sure this can be fixed by changing settings.

**Comment by hbenl** [comment]
I have added some improvements to version 2.7.0:
- I've added default pathMappings for Next.js projects, they should work out-of-the-box now
- I've fixed the Path Mappings Wizard so that it should work if you should need additional pathMappings

I noticed that I can't break on breakpoints in code that is executed on page load (usually they should be hit when you reload the page in Firefox) - but they are also not hit in Chrome Devtools.

Please try out this version and tell me if it works for you.

**Comment by hbenl** [comment]
This is really a bug in Next.js (as explained [here](https://github.com/zeit/next.js/issues/9471#issuecomment-556730491)), I've added a workaround in the Path Mappings Wizard and perhaps a workaround will eventually be added to Firefox, but this should be fixed in Next.js.

**Comment by h-jennings** [comment]
@hbenl Looks like it's working much better! I just tested it out in the same app and was able to get it up and running with my previous configuration, with only one additional path map (I was able to use the Path Mappings Wizard for this).

Excited to use this in future projects! Thanks so much for the hard work.

**Comment by jasonwilliams** [comment]
Its working better for me too, @hbenl what pathMappings did you add to make Next.js projects work? also what version did this get fixed in? 

Thanks
