### ISSUE TITLE
Connects vscode debugger to every tab browsed, even with url set. 

### ISSUE THREAD

**Issue by mrapogee** [firefox-devtools/vscode-firefox-debug#179]
It appears that as I'm browsing other pages then the one spec'ed in my vscode launch config, for example github.com, I hit any uncaught exception breakpoints on those pages as well as get logs from each tab I open in vscode.

This is my launch config:

```json
{
  "version": "0.2.0",

  "configurations": [
    {
      "name": "Attach FF",
      "type": "firefox",
      "request": "attach",
      "url": "http://localhost:5000",
      "webRoot": "${workspaceFolder}"
    }
  ]
}

```

**Comment by hbenl** [comment]
Yes, the debugger is automatically attached to every browser tab. You should use a separate Firefox window for regular browsing.

**Comment by hbenl** [comment]
FYI: with the new `tabFilter` configuration property you can now specify which tabs you want to attach to. The extension will also create a default `tabFilter` from your `url`, so it should work out-of-the-box.
