### ISSUE TITLE
pathMappings does not support wildcards

### ISSUE THREAD

**Issue by markusmauch** [firefox-devtools/vscode-firefox-debug#180]
Sometimes URL rewriting is used to insert variables into the URL like a version number. E.g. the URL ```https://example.com/app/v2.3.4/index.js``` is mapped to the physical resource ```app/index.js```. In such a case, wildcards would be helpful in the ```pathMappings``` setting:
``` 
{
  "pathMappings": [
    { "url": "https://example.com/app/*/", "path": "${workspaceFolder}/app/" }
  ]
}
```

**Comment by hbenl** [comment]
I have added support for wildcards in the URLs of pathMappings in version 2.7.0.
