### ISSUE TITLE
Restart not working properly

### ISSUE THREAD

**Issue by jasonwilliams** [firefox-devtools/vscode-firefox-debug#188]
Reproduction steps:
* VSCode (v1.43)
* Make sure you have the "Debugger for Firefox" (i'm using 2.7.0)
* Check out https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example
* npm install
* launch Server
* launch firefox debugger
Try to use the restart functionality

**Result**
Browser shuts down

**Expected behaviour (Debugger for Chrome 4.12.6)**
![debuggingChrome](https://user-images.githubusercontent.com/936006/75300426-b618b080-582f-11ea-9200-1048a454dfb4.gif)

**Unexpected behaviour (Debugger for Firefox 2.7.0)**
![debugging](https://user-images.githubusercontent.com/936006/75300440-bfa21880-582f-11ea-9bbf-26d0a1be352d.gif)

The browser shuts down instead of restarting.
Try doing the same with Chrome, it works as expected

**Comment by hbenl** [comment]
Actually this is working as intended. I know that the Chrome debugger works differently here, but I prefer it this way: if you make any changes to your debugging configuration, you need to restart the entire debugging session (and not just reload the browser) for them to take effect - so not restarting the entire debugging session could lead to confusion.
Try setting `reAttach` to `true` in your launch configuration, the browser will keep running in between debugging sessions, so the behavior of the restart button will look almost exactly the same as with the Chrome debugger (even though it isn't: the debug adapter will still be restarted, but that should be hardly noticeable).
