### ISSUE TITLE
skipFiles does not skip URL's correctly

### ISSUE THREAD

**Issue by AnrDaemon** [firefox-devtools/vscode-firefox-debug#189]
VS Code 1.43
ffdebug 2.7.0

Configured launcher:
```json
        {
            "type": "firefox",
            "request": "attach",
            "name": "FFdebug",
            "skipFiles": [
                "**/node_modules/**/*",
                "**/*.min.js"
            ],
            "log": {
                "fileName": "${workspaceFolder}/../Logs/ffdebug.log ",
                "fileLevel": {
                    "default": "Debug"
                }
            },
            "pathMappings": [
                {
                    "url": "https://devserver.example.lan/**/*.php",
                    "path": null
                }
            ]
        }
```

However, platform I'm debugging uses unique caching keys with static files, as it is common for many enterprise platforms, so the resulting URL looks like `/path/to/statics/jquery.min.js?v=somekey`.
And, perhaps unsurprisingly, won't be blackboxed.
I can get around it with something like `**/*.min.js**`, but honestly, if it's at all possible, I would like to avoid workarounds.
Another possibility is to path map every JS files' location manually. As you can imagine, it's not a very good idea, even if there's only a handful of them. I did it, but there's already 10 locations of that kind, and could be more, as project extensively using plugin system and every plugin may have its own additional UI elements. Which I also would usually blackbox, as I'm not really concerned with library code.

**Comment by hbenl** [comment]
Actually this was already working for files that could be mapped to files in your workspace, but I forgot to remove the query string for external URLs. It's fixed in version 2.8.0.
