### ISSUE TITLE
Unable to debug because packet type 'attach' is not recognized

### ISSUE THREAD

**Issue by Xp0s3d** [firefox-devtools/vscode-firefox-debug#191]
No matter what configuration I am using, I am unable to debug any code.

I am able to connect to the firefox (developer edition) instance (as I am getting the correct amount of opened tabs) but all breakpoints are unverified and in the log I am getting the following error: 

> DEBUG|000.280|RootActorProxy: Received 4 tabs
> DEBUG|000.280|RootActorProxy: Tab server1.conn0.tabDescriptor1 opened
> INFO |000.280|FirefoxDebugSession: Tab opened with url undefined
> DEBUG|000.281|TabActorProxy: Attaching to tab server1.conn0.tabDescriptor1
> DEBUG|000.281|DebugConnection: Sending request {"to":"server1.conn0.tabDescriptor1","type":"attach"}
> [...]
> WARN |000.284|TabActorProxy: Unknown message from TabActor: {"error":"unrecognizedPacketType","message":"Actor server1.conn0.tabDescriptor1 does not recognize the packet type 'attach'","from":"server1.conn0.tabDescriptor1"}

I updated all the options in about:config and debugging is enabled in the developer tools. The problem even persists when using the 'launch' parameter which launches a firefox instance and seems to connect like it should. Breakpoints aren't working though. The log shows the same error above aswell.

Would really appreciate any kind of help as it was working just a few days ago. The only thing that has changed since then was a small update of firefox which I am unable to revert and can't seem to find "old versions" as the installer will automatically install the newest version.

**Comment by hbenl** [comment]
Looks like there was a change in Firefox' remote debug protocol, I'll fix this soon.
In the meantime you can get old versions from [here](https://ftp.mozilla.org/pub/firefox/releases/) and you can prevent Firefox from automatically updating itself by setting `app.update.auto` to `false` in `about:config` (if you use a launch configuration you can add `"preferences": { "app.update.auto": false }` to your `launch.json`). Alternatively you can use the regular Firefox edition by setting `firefoxExecutable` in your `launch.json`.

**Comment by Xp0s3d** [comment]
Ok so I've tried to set the regular Firefox and all breakpoints where reached again.
Downloading an old version of developer edition somehow always ended up installing the newest version anyway so I was unable to try old versions (as it is working for versions < 75.0).
Is there any way to see if the debugger server is actually running correctly?

Appreciate the quick answer though!

**Comment by hbenl** [comment]
> Is there any way to see if the debugger server is actually running correctly?

If you're talking about the effect of the `-start-debugger-server` command line flag: if it is not working you'd see an error message like "connect ECONNREFUSED 127.0.0.1:6000` every time you try to start a debugging session.

I have a fix for this issue and will publish it as soon as it got reviewed by Mozilla.

**Comment by hbenl** [comment]
Fixed in version 2.7.1.
