### ISSUE TITLE
Open given URL on running Firefox instance when using "attach" launch configuration

### ISSUE THREAD

**Issue by AObuchow** [firefox-devtools/vscode-firefox-debug#194]
It would be greatly appreciated (for general UX reasons in VSCode and Eclipse IDE) if the running Firefox instance would open up the given URL when it's provided in a "attach" launch configuration. 

As it currently stands, the user has to manually type in the URL for the webserver they're running to start debugging their web app. 

If possible, it would probably be best to check if the requested URL to debug is already open in a tab, to prevent from opening it when the user already has it open.

**Comment by digitarald** [comment]
I like the idea; this would make debugging and iterating a lot easier.

**Comment by AObuchow** [comment]
Awesome :) I hope to see it implemented someday. From what I understand, this behaviour exists in the Chrome Debugger extension from VSCode.

**Comment by hbenl** [comment]
First of all, I don't think I can tell Firefox to open a new tab, but I could navigate one of the existing tabs.
I was thinking about implementing this as a VS Code command, that would save me the trouble of figuring out when to navigate to the given URL and in which tab:
- obviously navigating isn't necessary when one tab already shows the configured URL
- but what about "similar" URLs? e.g. the config says "http://localhost:3000/" but the tab is navigated to "http://localhost:3000/something"...? The user may need to be able to define which URLs to consider and which not.
- if there are multiple tabs open, the question becomes which one we should navigate

With a VS Code command the user could have full control over when and which tab to navigate. The only downside is that he has to explicitly call the command every time he wants to navigate (as opposed to some automatism that would be configured once and then works every time).
So, do you think a command would be good enough (or possibly even better as it wouldn't require any configuration)?

**Comment by hbenl** [comment]
Well, to implement the VS Code command I'll have to implement custom requests for the Debug Adapter protocol anyway, so you could use that.
Here's my current plan for these custom requests:
- one request would return all browser tabs with a `tabId`, the tab's `url` and a `threadId` if the tab is attached (I'll also need this request for another feature: allowing the user to attach to and detach from tabs during a debug session)
- the second request would allow you to navigate a tab (identified with its `tabId` from the first request) to a `url` given in the request (or the one given in the configuration, if the request doesn't contain a `url`)

With these requests you should be able to implement something corresponding to a VS Code command or you could even implement an automatic mechanism if you prefer that.

**Comment by mickaelistria** [comment]
That seems like a lot of integration effort for the client. Custom requests are always a lot of churn.
Also, it seems like with this proposal, you're expecting the client to decide of a tab to use.
The issue that was reported first is IMO a bug, ie the page doesn't open properly in some cases when attaching the debugger. I would expect that a simple `openURL` configuration flag in first debug parameter to open an URL after attaching the debugger could be enough to resolve the issue.

**Comment by hbenl** [comment]
> you're expecting the client to decide of a tab to use

Well, someone has to make the decision. The client can ask the user to make the decision, that's what I like about this solution. But I could also implement some (optional) logic to do this automatically.

> The issue that was reported first is IMO a bug, ie the page doesn't open properly in some cases when attaching the debugger.

Then you'd have to specify what the correct behavior should be (as it isn't obvious to me). If the debugger attaches to the browser, which has multiple tabs open and none of them is navigated to the URL given in the configuration: which one should be navigated? It's my impression that many users that use an "attach" configuration do so _because_ they have multiple tabs, one for debugging and the others for reading documentation etc. In that case navigating the wrong tab could be quite annoying.

By the way, if you do this with the Chrome debug adapter, the debug session will simply not start: after a delay of 10 seconds, it will abort with a lengthy error message containing "Can't find a valid target that matches \<url\>". I could implement that behavior, but I don't think it would be an improvement over the current situation.

**Comment by mickaelistria** [comment]
> If the debugger attaches to the browser, which has multiple tabs open and none of them is navigated to the URL given in the configuration: which one should be navigated?

I guess most users would be the happiest with the browser opening a new tab with the right URL.

> By the way, if you do this with the Chrome debug adapter, the debug session will simply not start: after a delay of 10 seconds, it will abort with a lengthy error message containing "Can't find a valid target that matches <url>". I could implement that behavior, but I don't think it would be an improvement over the current situation.

I agree that such behavior is IMO not worth being implemented. I think the suggestion above is more interesting and worth the effort as it will bring joy to more developers.

**Comment by hbenl** [comment]
> I guess most users would be the happiest with the browser opening a new tab with the right URL.

Yes, I agree that would be the best solution. However, I don't think I can open a new tab through the Firefox remote debug protocol :(

**Comment by mickaelistria** [comment]
> I don't think I can open a new tab through the Firefox remote debug protocol :(

Maybe not, but I believe it's possible to open a tab for a given URL in existing firefox instances with CLI, isn't it? At least, it's the default for me when I type stuff like `firefix www.github.com`: a new tab open in my current instance.

**Comment by hbenl** [comment]
Ha! I didn't think of that. Or I did (briefly), but at first I thought it wasn't possible to tell Firefox where to open the tab if multiple instances are open (which is not unusual when you're using one instance for debugging), but I just found that `firefox --profile <profileDir> <url>` will open a new tab in the window that uses the given profile directory (and the debug adapter knows which profile directory its Firefox instance uses). So I can do this, thanks for the idea!
So now I'll just have to decide how it should be configured: should this become the default or optional? Perhaps it makes sense to only enable it when you're using a whitelist for the tabs you want to attach to and no tab matches the whitelist (see #207, which I am currently implementing). Perhaps there should be a whitelist by default (e.g. if the url in your configuration is `http://localhost:3000/index.html` the default whitelist could be `http://localhost:3000/*`). Any thoughts?

**Comment by mickaelistria** [comment]
Good you think my proposal is viable, I wasn't really confident in it ;)
IMO, from the Eclipse IDE, we could implement a way for user to explicitly select option to "Automatically open tab for URL http://... if no existing tab matches"; we'd probably turn it on by default and users could opt-out. We'll probably explicitly pass the option in all cases, whether it's true or false, so the default behavior of the LS in case option isn't set wouldn't matter much (and consequently, you can just pick what you think is the best default when option isn't set, as we should always override it).
Our of that, I don't think we need more control, or restriction, or whitelist/blacklist at the moment for the known user stories we support. Maybe all that will come some time later...

**Comment by hbenl** [comment]
This is the behavior that I have implemented in 2.9.0:
- by default only tabs whose URL matches the one from the attach configuration (minus the last path segment, see my previous comment) will be attached to
- if there is no tab with a matching URL, a new tab will be opened
- I made this the new default behavior because it is probably what most users will expect
- to get the old behavior back you can add `"tabFilter": "*"` to your configuration
- opening a new tab only works if the debug adapter uses the same Firefox executable and the same profile as the running Firefox instance. In most cases the debug adapter should be able to figure these out, if necessary you can specify `firefoxExecutable` or `profileDir` in your attach configuration

**Comment by AObuchow** [comment]
Thank you so much @hbenl :D I look forward to trying this out.
Eclipse Wild Web Developer users will benefit a lot from this :)

**Comment by mickaelistria** [comment]
Thanks @hbenl . The implemented behavior seems really promising!
