### ISSUE TITLE
Readme.md option missing a dash

### ISSUE THREAD

**Issue by SpineEyE** [firefox-devtools/vscode-firefox-debug#195]
Hi,
there is a typo (or maybe referring to an older version) in the Readme. It should be `--start-debugger-server` with 2 dashes, not `-start-debugger-server`

**Comment by hbenl** [comment]
That's not a typo: Firefox accepts both single and double dashes on all platforms, I decided to follow the [Firefox documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options) for the command line options.
