### ISSUE TITLE
Wrong output in VS code

### ISSUE THREAD

**Issue by jluisgarcia** [firefox-devtools/vscode-firefox-debug#197]
**Environment**
Ubuntu 18.04.4 LTS
VScode 1.43.2
Debugger for Firefox 2.7.1

**Description**

Strange as it seems, different results from Firefox Console and VScode Console are shown.
Inside Firefox, output is correct. Output is a _Set_. Inside VS code, it is not correct. It shows _Array_.

![fire](https://user-images.githubusercontent.com/24752182/78840065-1dfb1300-79fa-11ea-9e97-252ffec50a73.png)

**Comment by digitarald** [comment]
Build-in DevTools use their own representation for types; while VS Code might fall back to common ones.

@hbenl is this something that gets lost in translation in the protocol, or the extension?

**Comment by jluisgarcia** [comment]
@digitarald  With Chrome and "Debugger for Chrome" extension, it works just fine.

**Comment by jluisgarcia** [comment]
Because it is related to wrong output in VSstudio code as well, I would like to add another case. I am actually the reporter of this question in stackoverflow.
https://stackoverflow.com/questions/61043113/symbol-as-key-identifier-for-javascript-objects-in-firefox/61043404#61043404
The right output is shown in Firefox console, but fails also in VScode console.

**Comment by hbenl** [comment]
@digitarald The representation is generated by the adapter [here](https://github.com/firefox-devtools/vscode-firefox-debug/blob/master/src/adapter/adapter/preview.ts). Could you point me to the equivalent code in Firefox' built-in debugger? There's probably more problems like this in the adapter's code, so it would be great if I had a more thoroughly-tested code that I can use as a guide.

**Comment by digitarald** [comment]
The code is in [devtools reps](https://searchfox.org/mozilla-central/source/devtools/client/debugger/packages/devtools-reps/src), which I am not sure if it helps to format output for vs code as it focuses on providing react components.

**Comment by hbenl** [comment]
Fixed in version 2.8.0.
@jluisgarcia The bug described on stackoverflow is actually a bug in VSCode: I send both symbol-keyed properties to VSCode, but (since they have the same name) it only shows one of them. You can also see this bug when using the Chrome debug adapter for VSCode.
