### ISSUE TITLE
[Feature Request] Allow “stable”, “nightly” and “developerEdition” in executable

### ISSUE THREAD

**Issue by jasonwilliams** [firefox-devtools/vscode-firefox-debug#205]
This would make it a lot easier to switch without finding the absolute path to the executable.
 The VSCode JS debugger allows for this and it makes life a lot easier https://github.com/microsoft/vscode-js-debug#other-small-things

**Comment by hbenl** [comment]
I added this to version 2.9.0, with one small modification: I used "developer" instead of "developerEdition".
Thanks for the suggestion, this is useful indeed.
