### ISSUE TITLE
Close Firefox window / terminate firefox process when debugging is terminated

### ISSUE THREAD

**Issue by N247S** [firefox-devtools/vscode-firefox-debug#219]
Goodday all,

I tried to dig around for a way to terminate firefox when de debugger is terminated (just like the ChromeDebugger does).
I couldn't find a way either via the commandline options, nor in the extension settings.
Am I missing something, or is this something that is not possible?

I would love to hear any workarounds!

**Comment by hbenl** [comment]
Have you tried setting `reAttach` to `false` in your launch configuration? That should terminate Firefox at the end of the debug session.

**Comment by N247S** [comment]
That seems to work. I thought that option would only attempt to reconnect once a debug session closed forcefully/with exception.

Thanks for the hint!
