### ISSUE TITLE
Unexpected? error on macOS when setting `keepProfileChanges` and `reAttach` to `true`.

### ISSUE THREAD

**Issue by watters** [firefox-devtools/vscode-firefox-debug#220]
I'm getting this error:

`On MacOS, "keepProfileChanges" is only allowed with "reAttach" because your profile may get damaged otherwise`.

Which looks to be generated by [code added a few weeks ago](https://github.com/firefox-devtools/vscode-firefox-debug/commit/534040d27b13be6ea18313d3553eb8845d20cb70#diff-f3bab32186e7d500eff76152df222c62R132-R138):

```javascript
if (os.platform() === 'darwin') {
    if (!config.reAttach) {
        detached = false;
    } else if (config.keepProfileChanges) {
        throw 'On MacOS, "keepProfileChanges" is only allowed with "reAttach" because your profile may get damaged otherwise';
    }
}
```

The relevant settings in my `launch.json` look like:

```
      "reAttach": true,
      "keepProfileChanges": true
```

My impression from the error message's phrasing "is only allowed with" suggests that _both_ should be true. However, the code throws the error if both are true.

If the current behavior of the code is correct, it may be worth considering making the error message more explicit about the expected values for the config options, e.g. 'On macOS, "keepProfileChanges" is only allowed when "reAttach" is set to "false" because your profile may get damaged otherwise'.

**Comment by hbenl** [comment]
Unfortunately it is the code that is incorrect and the documentation is correct.
I'll fix this in the next release.

**Comment by watters** [comment]
Thank you!
