### ISSUE TITLE
Sync vscode debugger with Firefox debugger

### ISSUE THREAD

**Issue by koldou98** [firefox-devtools/vscode-firefox-debug#222]
I have recenty switched from Edge debugger to Firefox debugger. The first thing I noticed is that the debugger tab does not show in Firefox debugger as it does in Edges debugger.
![imagen](https://user-images.githubusercontent.com/48926759/88923027-52c4fb80-d271-11ea-97b9-a36bf7ebbee0.png)

However, in Firefox all the tab freezes looking like the web browser is not responding. Moreover in this state, Firefoxdevelopers tools can not be opened.

I wonder if the breakpoint set up in vscode could be seen in Firefox debugger.

**Comment by hbenl** [comment]
Sorry, this isn't possible: Firefox is designed to keep the debugging sessions (the one in VS Code and the one in Firefox devtools) separate, so neither can see the other session's breakpoints, pauses, etc.
