### ISSUE TITLE
Browser's console stays empty

### ISSUE THREAD

**Issue by keckelt** [firefox-devtools/vscode-firefox-debug#225]
Hi!

Since this week or so the console of my Firefox Developer Edition (v81.0b3) stays empty while debugging. All the log messages are displayed in VS Code's Debug Console only.

Debugger for Firefox has v2.9.1 and VS Code has v1.48.2

I've already checked if I accidentally set some filters:
![image](https://user-images.githubusercontent.com/10337788/91534516-f0aff280-e911-11ea-808a-b32700f34f2c.png)

When I simply open a second tab (i.e. a page not debugged) console logs are visible in browser for this second tab.

Any ideas?

**Comment by keckelt** [comment]
Also, a manual `console.log` is not printed:
![image](https://user-images.githubusercontent.com/10337788/91535718-e2fb6c80-e913-11ea-8efa-ca338ff4e5b6.png)

**Comment by jeandat** [comment]
Same thing for me including with latest developer edition (81.0b4 (64 bits)).
I tried with reAttach enabled/disabled, it doesn't change a thing.
Logs are visible in vscode console only.
Of course, logs are visible in firefox console when FDE is launched manually.
Running it from vscode debugger make console.log() statements invisibles.

**Comment by keckelt** [comment]
Apparently this is caused by the Firefox update.

Downgrading the debugger extension to v2.9.0 (the previous version) has no effect.
Downgrading [Firefox to v80](https://www.chip.de/downloads/Firefox-Developer-Edition-64-Bit_35450182.html) (80.0b1) shows the log messages in both VS Code and the browser.

**Comment by MBODM** [comment]
Exactly same here.

Extension: VS Code Debugger for Firefox 2.9.1
IDE: VS Code 1.49.2
Browser: Firefox 81.0

Error desc:

- Pressing F5 in VS Code leads to using launch.json in .vscode folder. Content of launch.json:
- `{
-     "configurations": [
-     {
-         "type": "firefox",
-         "request": "launch",
-         "reAttach": true,
-         "name": "Firefox",
-         "file": "${workspaceFolder}/index.html"
-     }
-     ]
- }`
- 
- next thing



I assume it either has something to do

**Comment by keckelt** [comment]
Updated to Firefox Developer 82.0b4 today and log messages are appearing in both VS Code and FF again.

**Comment by MBODM** [comment]
> 
> 
> Updated to Firefox Developer 82.0b4 today and log messages are appearing in both VS Code and FF again.
> 
> Note: I did not try any other other v82 release before that one.

Yep, fixed it. At least here on my screen. :) Thx for the quick answer and sorry for the late reply. :)

**Comment by mike-lischke** [comment]
This has been fixed in version 2.9.3.
