### ISSUE TITLE
Path Mapping Wizard shows success message after failing to add pathMapping to launch.json which is invalid JSON

### ISSUE THREAD

**Issue by 3nuc** [firefox-devtools/vscode-firefox-debug#228]
### Repro
1. Create a launch.json which is not valid json ([example](https://gist.github.com/3nuc/b295e6ab11e90b33758a4e7927bfbf22) - see lack of comma at line 20)
2. Set a breakpoint in a file that will trigger Path Mapping Wizard notification that suggests adding a new pathMapping automatically
3. Click button in notification so Path Mapping Wizard attempts to add a new pathMapping entry to launch.json

vscode 1.50.0-insider in WSL2 Ubuntu 18.04, vscode-firefox-debug 2.9.1

### What happens after repro
launch.json stays the same, no path is added to the invalid json, but the succes notification "path mapping added, restart your debug session" appears

### What should happen after repro
launch.json stays the same, but an error notification should be shown saying "can't add pathMapping to launch.json which is not valid JSON. Check the Problems tab while viewing launch.json for details"

**Comment by hbenl** [comment]
I have added an error message in version 2.9.2
