### ISSUE TITLE
Unwanted pathMapping suggestion on breakpoints

### ISSUE THREAD

**Issue by Spown** [firefox-devtools/vscode-firefox-debug#230]
Not all breakpoints should necessarily belong to Firefox Debugger. I use 2 debuggers simultaneously (Node (server) and Firefox (client)) and every time I set a breakpoint in a server-side file while Firefox Debug is active - it spams me with this popup. 

![Code_2020-10-13_17-38-05](https://user-images.githubusercontent.com/3817672/95883427-34a06f00-0d7b-11eb-807e-daacd54e6b9e.png)

And it doesn't understand "no". It also spams the popup, when I remove a breakpoint there as well.

How do I get rid of it?

Thank you.

**Comment by hbenl** [comment]
> How do I get rid of it?

Set `suggestPathMappingWizard` to `false` in your launch configuration.
