### ISSUE TITLE
webRoot?

### ISSUE THREAD

**Issue by Yuri6037** [firefox-devtools/vscode-firefox-debug#234]
What is this webRoot option? When running a server you only have an URL?

I currently have to set it to /tmp in order for VSCode to succeed debugging a React app. Could you either set a default or make this property optional?

**Comment by hbenl** [comment]
`webRoot` specifies the path of the directory that corresponds to the URL in the launch configuration. In most cases it is set to `"${workspaceFolder}"`. I'll make it default to that value in the next release.

**Comment by Yuri6037** [comment]
Thank you

**Comment by hbenl** [comment]
Fixed in 2.9.2
