### ISSUE TITLE
Please add global default port setting

### ISSUE THREAD

**Issue by cxxcoder** [firefox-devtools/vscode-firefox-debug#237]
I think it would be useful to add a global setting for the port which is used if the port is not defined in the project launch configuration.
The default port 6000 clashes with X-Server (for WSL on Windows).
However, explicitly setting the port in the launch configuration of every project makes no sense because this problem is scoped to the system.
Adding

	"firefox.port": ...

to settings.json or launch.json in VSCode config folder does not seem to work.

**Comment by hbenl** [comment]
I have added this in version 2.9.2
