### ISSUE TITLE
Ubuntu: Only snap installed version of Firefox can be launched

### ISSUE THREAD

**Issue by user-0209** [firefox-devtools/vscode-firefox-debug#242]
I'm trying to setup for debugging an Angular 10 web app with VsCode and Firefox. Launch configuration for Chrome worked out of the box, but couldn't make Firefox work. Several problems:
1. It doesn't start Firefox: The busy indicator in Code would move for a couple if seconds, then launching stops. Tried several options in launch config, but nothing helped. After all, I found that it will start Firefox, if it is installed as a snap iso using apt.
2. Once it launched, a dialog box appears: Your Firefox profile cannot be loaded. It may be missing or inaccessible. By chance stumbled over a note to use the tempDir option and point it into a folder within my home directory, so it becomes accessible by the snap.
3. Next, another dialog would appear: connect ECONNREFUSED 127.0.0.1:6000. Had to configure a timeout of 20s or more (I'm not really on a slow machine). 

So finally my launch configuration for Firefox is:
```
        {
            "name": "Launch Firefox",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "url": "http://localhost:9000/",
            "webRoot": "${workspaceFolder}",
            "tmpDir": "~/tmp",
            "timeout": 30,
            "clearConsoleOnReload": true,
            "log": {
                    "consoleLevel": {
                        "default": "Info"
                    },
                    "fileName": "${workspaceFolder}/vscode-firefox-debugger.log",
                    "fileLevel": {
                        "default": "Debug"
                    }
            }
        },

```
The log in case of failing at 1. is not much helpful, I guess:
```
DEBUG|002.234|BreakpointsManager: Setting 2 breakpoints for /home/LOCAL/ronald/Sandboxes/askev/portal-2/src/main/webapp/app/material/members/member-table/member-table.component.ts
DEBUG|002.235|BreakpointsManager: Setting 2 breakpoints for /home/LOCAL/ronald/Sandboxes/askev/portal-2/src/main/webapp/app/entities/user-profile/user-profile.component.ts
DEBUG|002.298|FirefoxDebugAdapter: Setting exception filters: []
DEBUG|002.323|FirefoxDebugAdapter: 0 threads
INFO |002.340|FirefoxDebugSession: Connection to Firefox closed - terminating debug session
```
Firefox: 84.0.2 (both installs)
Ubuntu: 20.04.1 amd64
Desktop: budgie
VsCode: 1.52.1

**Comment by hbenl** [comment]
This is a problem in the snap version of VS Code. I have added a workaround in version 2.9.2, so it works with the regular version of Firefox again.
