### ISSUE TITLE
Breakpoint doesn't work well

### ISSUE THREAD

**Issue by Oops625** [firefox-devtools/vscode-firefox-debug#245]
There is a strange problem occured when i try to start a debugging session: the breakpoint only works when i refresh the page twice at a time.

Here is the relevant info:
Firefox: **86.0 (64 bit)**
vs code: **1.53.0 on window_NT x64**
extension: **v2.9.2**

Is there exists a corresponding solution?

**Comment by hbenl** [comment]
This is fixed in version 2.9.3
