### ISSUE TITLE
Javascript no longer outputs to VS Code's Debug Console

### ISSUE THREAD

**Issue by xiaoandtell** [firefox-devtools/vscode-firefox-debug#247]
It used to output everything in the browser's console to VSCode's Debug Console view. After I updated from Firefox 72 to firefox 86, VSCode's Debug Console view is empty. 

Here is my launch configuration:

			"name": "FFox index.html",
			"type": "firefox",
			"request": "launch",
			"file": "${workspaceFolder}/index.html",
			"keepProfileChanges": true,
			"profileDir": "${workspaceFolder}/_x/profileDirDebug",
			"reAttach": true

I've tried to no avail: 
			"clearConsoleOnReload": true, (this only prints "Console was cleared" in VS Code's debug console, no other expected output)
			"showConsoleCallLocation":true 

- Console outputs as expected in the browser's Console view.
- I've tried uninstalling and reinstalling the extension to no avail.

**Comment by chrisv5** [comment]
Same problem here. So glad to find this bug report, I already thought that I lost my mind

**Comment by hbenl** [comment]
This is fixed in version 2.9.3
