### ISSUE TITLE
[FR] Show base file names for web workers in the call stack

### ISSUE THREAD

**Issue by mike-lischke** [firefox-devtools/vscode-firefox-debug#251]
Because web worker debugging was broken and I had to temporarily use Chrome for debugging, I got used to a nice little feature, which I now miss after I switched back to FF: the call stack only shows workers with a running number:

<img width="412" alt="Bildschirmfoto 2021-04-01 um 10 21 59" src="https://user-images.githubusercontent.com/2398704/113265185-1e0fb500-92d4-11eb-839d-b57cfc110851.png">

while Chrome displays:

<img width="458" alt="Bildschirmfoto 2021-04-01 um 10 23 21" src="https://user-images.githubusercontent.com/2398704/113265363-56af8e80-92d4-11eb-8b32-26f97b1e27af.png">

which greatly helps to identfiy which worker type is currently running.

My feature request is hence: change the display in the FF debug extension to show something similar like the Chrome tools do.

**Comment by hbenl** [comment]
I have added the URLs to the thread names in version 2.9.4. I would have liked to also implement the hierarchical display that the Chrome debug adapter shows, but it looks like that would require a big refactor.
