### ISSUE TITLE
Latest VS Code update breaks extension

### ISSUE THREAD

**Issue by ironman820** [firefox-devtools/vscode-firefox-debug#268]
I am running Endeavour (Arch) Linux with the latest version of VS Code (1.62.1). I have installed the developer edition of Firefox and have set the executable location in VS Code appropriately. While running Code v1.62 I was able to launch and attach to Firefox instances with the debugger. Since the update, every time I try to launch or attach to a Firefox instance, I am given the error "connect ECONNREFUSED 127.0.0.1:6000". To troubleshoot, I manually opened Firefox, updated the settings in about config, and restarted the program and still cannot attach. I'm unsure where to look next because it doesn't appear to be logging anything.

**Comment by Nukiloco** [comment]
Same here, it's completely broken for me.

**Comment by trombipeti** [comment]
Same here, using Windows 10, VS Code 16.2.1 and Firefox 94.0.1.
To me, it seems like there's trouble starting a new instance of firefox.

I could use the extension in "attach" mode though. Still, not what I'd like.

**Comment by novarider** [comment]
Same problem on Windows 10, VS Code 16.2.1 and Firefox 94.0.1.

**Comment by Nukiloco** [comment]
For people having this issue, here is a current work around if you want to debug with the launch option for VSCode. Note I made this for Windows though I think it can be easily modifiable for Linux and other operating systems as well.

tasks.json
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Launch Firefox",
            "type": "process",
            "windows": {
                "command": "C:/Program Files/Firefox Developer Edition/firefox.exe",
                "args": [
                    "-start-debugger-server", "30000",
                    "-url", "http://localhost:3000"
                ]
            },
        }
    ]
}
```

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Firefox",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "port": 30000,
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}",
            "pathMappings": [
                {
                    "url": "http://localhost:3000",
                    "path": "${workspaceFolder}"
                }
            ]
        },
    ]
}

```

**Comment by ironman820** [comment]
Here's a modified copy that should work on Windows or Linux. Linux users might need to update the install location. It was able to launch the application on the default port and connect just fine with the custom task. Also, for whatever reason, I could not get it to connect while the task was running in Linux (haven't tested it on Windows) without setting isBackground to true in the task config. I think it's waiting for the task to complete, and it can't do that while Firefox is running.

tasks.json

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Launch Firefox",
            "type": "shell",
            "windows": {
                "command": "C:/Program Files/Firefox Developer Edition/firefox.exe"
            },
            "linux": {
                "command": "/usr/lib/firefox-developer-edition/firefox"
            },
            "args": [
                "-start-debugger-server",
                "-url", "http://localhost:3000"
            ],
            "isBackground": true
        }
    ]
}
```

launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Firefox",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "preLaunchTask": "Launch Firefox",
            "internalConsoleOptions": "openOnSessionStart",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}",
            "pathMappings": [
                {
                    "url": "http://localhost:3000",
                    "path": "${workspaceFolder}"
                }
            ]
        }
    ]
}
```

**Comment by laohouppa** [comment]
same problem on Windows, I tried your solutions, it still does not work

**Comment by devoNOTbevo** [comment]
This ended up working for me - ended up using `command` instead of `linux.command` on mac and also took off `isBackground` in order to get rid of "the specified task can not be watched" error from vscode.

**Comment by devoNOTbevo** [comment]
> same issue: Mac OSX 12.0.1 (21A559), Firefox Developer Edition 95.0b6, VS Code Version: 1.62.2
> 
> This ended up working for me - ended up using `command` instead of `linux.command` on mac and also took off `isBackground` in order to get rid of "the specified task can not be watched" error from vscode.
> 
> edit: this got it to "run", but breakpoints are still not working in a React app.
> 
> `enableCRAWorkaround` true and `pathMappings` set.

I ended up re-enabling `isBackground: true` and now breakpoints work.

**Comment by silviomarazzato** [comment]
Same issue: Fedora 34, Firefox 94.0, VS Code 1.62.2

With the work around that uses tasks, Firefox does not open (also using `"isBackground": true`). only by running it with the command `/usr/bin/firefox -p debug -start-debugger-server -url http://localhost:8100` and doing the attach does it work.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Firefox",
            "request": "attach",
            "type": "firefox",
            "url": "http://localhost:8100",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```
