### ISSUE TITLE
Debugger for webstorm and or other editors

### ISSUE THREAD

**Issue by petterhoel** [firefox-devtools/vscode-firefox-debug#270]
Is there any ongoing initiative or interest in having a similar experience for webstorm users and/or other editors?

I understand this is the vscode specific repository, please if another repository is a better place for this inquiry?

**Comment by hbenl** [comment]
The core of this extension implements the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/) and is [published on npm](https://www.npmjs.com/package/firefox-debugadapter) for that purpose, so any IDE that supports this protocol can make use of it. In fact it is being used by the [Wild Web Developer](https://github.com/eclipse/wildwebdeveloper) extension for Eclipse.
Unfortunately Jetbrains doesn't seem to be interested in supporting this protocol.
