### ISSUE TITLE
Extension doesn't receive webpack URLs

### ISSUE THREAD

**Issue by layday** [firefox-devtools/vscode-firefox-debug#271]
Thanks for this extension.  I've tried using it with an Angular app compiled with Webpack.  All of my hosts appear under "loaded scripts" apart from Webpack's.  My configuration is:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch localhost",
      "type": "firefox",
      "firefoxExecutable": "C:/Users/[...]/scoop/apps/firefox-developer/95.0b12/firefox.exe",
      "request": "launch",
      "reAttach": true,
      "url": "http://localhost:4200/",
      "webRoot": "${workspaceFolder}",
      "pathMappings": [
        {
          "url": "webpack:///",
          "path": "${webRoot}"
        }
      ],
      "log": {
        "fileName": "${workspaceFolder}/vscode-firefox-debug.log",
        "fileLevel": {
          "default": "Debug"
        },
        "consoleLevel": {
          "SourceMappingThreadActorProxy": "Debug",
          "default": "Warn"
        }
      }
    }
  ],
}
```

Debug view in Firefox:

<img width="106" alt="ff" src="https://user-images.githubusercontent.com/31134424/143566745-9c2e2c92-cfd5-4e58-9262-219d86a953ac.png">

Loaded scripts in Code:

<img width="132" alt="vscode" src="https://user-images.githubusercontent.com/31134424/143566779-0f9dcbbd-0196-45fe-8f76-d9824476e5af.png">

The extension is also unable to map Angular modules using the path wizard.  Looking at the log, it does not appear to receive Webpack URLs from Firefox at all (!), so there's nothing for it to map.  Would you know why that might be happening?

**Comment by MetricMike** [comment]
I'm running into this issue as well, but couldn't see anything that jumped out when running with log at debug. Happy to help troubleshoot, but could use some help getting pointed in the right direction. Chrome/Edge work-out-of-the-box, but like layday mentioned, Firefox doesn't appear to be sending Webpack URLs at all for the vscode debugger to map.

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "name": "Launch localhost",
            "url": "http://localhost/index.html",
            "webRoot": "${workspaceFolder}"
        },
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```

**Comment by layday** [comment]
This appears to have been an issue with Webpack on Node 17 where requests for source maps were refused by the server.  Starting `ng serve` with `--host=127.0.0.1` fixed it for me. It would be helpful if the extension reported failing requests.

**Comment by layday** [comment]
Thanks again for the debugger extension - I'll close this since it isn't an issue with the extension.
