### ISSUE TITLE
Since Firefox 96 (maybe 95) I cannot set breakpoints in code

### ISSUE THREAD

**Issue by jeandat** [firefox-devtools/vscode-firefox-debug#272]
I'm using firefox to debug my angular project for a few years now but since a week or two I cannot use the debugger anymore.
It works perfectly with chrome though.

When I launch a session via the run and debug module of vscode, firefox starts but:
- the debug console is empty
- I cannot set any breakpoint in code
- clicking the refresh button in vscode does not work
- clicking the stop button kill the debug session but do not kill firefox

It seems they are not linked anymore. Others do not have this issue I guess as I do not find an open issue in this repo or references on the web. Yet nothing changed on my part except updating firefox.

Don't know what to check at that point. Any help appreciated. Thanks.

My conf:

```
{
      "name": "Launch Firefox against localhost",
      "type": "firefox",
      "request": "launch",
      "reAttach": true,
      "url": "https://127.0.0.1:8080",
      "webRoot": "${workspaceFolder}",
      "profile": "default",
      "keepProfileChanges": true,
  },
```

VSCode: 1.63.0
Firefox: 96.0b3
OS: macOS 11.6.1

**Comment by Dunexus** [comment]
Also, when trying to run the path mapping wizard, it fails with this message : `Firefox didn't load any sources in the active debug session yet`

**Comment by duffimc** [comment]
Same problem with stand alone version of Firefox Developer edition. 
My conf:

```
{
	"configurations": [
		{
			"name": "Launch localhost",
			"type": "firefox",
			"request": "launch",
			"reAttach": true,
			"url": "http://localhost:4200",
			"pathMappings": [{
				"url": "http://localhost:4200",
				"path": "${workspaceFolder}"
			}],
			"firefoxExecutable": "/home/rverde/dev/firefox-dev/firefox",
			"profileDir": "/home/rverde/dev/firefox-dev"
		}
	]
}
```

**Comment by pablofierro** [comment]
👋 I'm experiencing similar issues where my project is no longer working with Firefox 96 (dev edition), I'm seeing the following logs:

```
WARN |000.105|TabActorProxy: Unknown message from TabActor: {"from":"server1.conn14.child10/windowGlobalTarget2","error":"Error","message":"Spec for 'windowGlobalTarget' specifies a 'attach' method that isn't implemented by the actor","fileName":"resource://devtools/shared/protocol/Actor.js","lineNumber":170,"columnNumber":17}
```

**Comment by chriskemp** [comment]
> 👋 I'm experiencing similar issues where my project is no longer working with Firefox 96 (dev edition), I'm seeing the following logs:
> 
> ```
> WARN |000.105|TabActorProxy: Unknown message from TabActor: {"from":"server1.conn14.child10/windowGlobalTarget2","error":"Error","message":"Spec for 'windowGlobalTarget' specifies a 'attach' method that isn't implemented by the actor","fileName":"resource://devtools/shared/protocol/Actor.js","lineNumber":170,"columnNumber":17}
> ```

Exactly the same here; I can't set breakpoints since Firefox dev edition upgraded to 96b and the log shows the same problem.  Forcing a downgrade to Firefox 95 allows breakpoints to be set again.

**Comment by jeandat** [comment]
Just tested `96.0b5`, still not working.

**Comment by jeandat** [comment]
@hbenl Do you know in which version of firefox your PR will be merged?

**Comment by hbenl** [comment]
@jeandat The PR doesn't go into Firefox but into version 2.9.6 of this VS Code extension, which I have just published.
