### ISSUE TITLE
Couldn't find the Firefox executable

### ISSUE THREAD

**Issue by trombipeti** [firefox-devtools/vscode-firefox-debug#279]
VSCode 1.66
Windows 10
Firefox is installed in "C:\Program Files\Mozilla\Firefox\firefox.exe"

When I try to start the debugger, I get the popup telling me to specify firefoxExecutable in launch.json.
If I do that with the path above, it works somehow.

I do still think that this is a bug, because that is _the_ path to firefox in most cases so the plugin _should_ be able to find it.

**Comment by TriMoon** [comment]
> I do still think that this is a bug, because that is _the_ path to firefox in most cases so the plugin _should_ be able to find it.

That's only true for M$ platforms, it varies a lot on other types...
But I agree it should by default try to find the appropriate executable in the `PATH` of the platform...

**Comment by hbenl** [comment]
> I do still think that this is a bug, because that is the path to firefox in most cases so the plugin should be able to find it.

Actually it is not, the default install locations on Windows are "C:\Program Files\Mozilla Firefox\firefox.exe" and "C:\Program Files (x86)\Mozilla Firefox\firefox.exe" (i.e. there is a folder called "Mozilla Firefox" but you have a folder called "Mozilla" with another folder "Firefox" in it). If Firefox is installed in one of those locations, the extension will automatically find it.

**Comment by trombipeti** [comment]
Thanks, you're right - it's a work laptop and for whatever reason that's where Firefox is installed. Doesn't seem to make any sense though.
Anyways, I've solved it by creating a symlink under "C:\Program Files".

**Comment by mriddi** [comment]
Help pleas with remote development: i have vscode with this extension on my PC, i start connect to remote host, open folder with firefox sources with compiled bins and try to launch debug, but it starts firefox installed on my local machine, not remote! How can I solve it? If in launch.json set path to bin in remote machine like /home/user/firefox/obj/dist/bin/firefox, it gives me error 
Couldn't find the Firefox executable (seems that it looks it on local PC).
