### ISSUE TITLE
Breakpoint hit, but not shown in the code

### ISSUE THREAD

**Issue by marekpetak** [firefox-devtools/vscode-firefox-debug#286]
Breakpoint hit, but not shown in the code editor, nor in the CALL STACK window, but CALL STACK windows tells me that 'PAUSED ON BREAKPOINT'.  Cannot step through the code at all.

Firefox Dev 102.0b5 (64-bit)
Debugger for Firefox 2.9.6

![image](https://user-images.githubusercontent.com/7045818/172827732-effe5b6e-bbea-4ec7-b7d0-21c98938ecc1.png)

**Comment by hbenl** [comment]
This will be fixed by #289 (awaiting code review).
