### ISSUE TITLE
Stopping debug should exit launched Firefox/Thunderbird processes

### ISSUE THREAD

**Issue by vanowm** [firefox-devtools/vscode-firefox-debug#295]
When `request` is to `launch` I'd expect the debugger have full control for launched processes, so when debugger stopped, the processes it launched should also be stopped (at least this is how debugging with MS Edge works)

Right now, every time I need restart the debugger, I have to manually quit the Thunderbird (which also doesn't close automatically devtools/console)

**Comment by jaysonsosweet** [comment]
Absolutely agreeing on this ! Shame we have to close the window manually.

**Comment by cyd3r** [comment]
I think this has been asked and answered before in #219 
Set `reAttach` to `false` in you launch config.
