### ISSUE TITLE
Get your plugin listed at https://developer.mozilla.org/en-US/docs/Tools

### ISSUE THREAD

**Issue by jnachtigall** [firefox-devtools/vscode-firefox-debug#3]
I think you should get in contact with mozilla devtools team to get your plugin listed at some page below https://developer.mozilla.org/en-US/docs/Tools

I could only find https://wiki.mozilla.org/Remote_Debugging_Protocol and https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging which both do not seem appropriate to me.

AFAICS there's currently no "list of clients" of the debugging protocol as chrome has https://developer.chrome.com/devtools/docs/debugging-clients 

If you want I could add a ticket at bugzilla so that mozilla adds one?

**Comment by hbenl** [comment]
I highly doubt that they'll list it - I can't find any Mozilla page promoting a third-party tool anywhere. You're free to try, of course (and I'd be very grateful if you succeed).

**Comment by jnachtigall** [comment]
@hbenl ok, I'll ask. Do you know any similar debugging tools that use Firefox's remote debugging prototol? The more plugins, the more likely they'll add a page. AFAIK even [Intellij does not support this](https://www.jetbrains.com/help/idea/2016.1/debugging-javascript.html#d959720e371 ): 

> Due to the recent crucial changes in the Firefox architecture, neither remote debugging nor standard for IntelliJ IDEA local debugging work for Firefox. This procedure is a temporary solution and is applicable to Firefox versions 33, 34, and 35.

**Comment by hbenl** [comment]
The only one I know is [the other debug adapter for VS Code](https://marketplace.visualstudio.com/items?itemName=yurydelendik.firefox-debug) (which was started by a Mozilla developer "to quickly add basic debugger support to be more comfortable with vscode" and hasn't been updated since its initial release 2 months ago).

**Comment by jnachtigall** [comment]
I've created https://bugzilla.mozilla.org/show_bug.cgi?id=1299111 for this. Let's see :)

**Comment by rugk** [comment]
I am sure they have nothing against adding it there. Just wonder why so few IDEs support it. AFAIK it is even nearly the same protocol as Chrome/ium uses.

**Comment by hbenl** [comment]
> AFAIK it is even nearly the same protocol as Chrome/ium uses.

Not really - there are some basic structural similarities between the two protocols, but when you look at the details, they're quite different.

> Just wonder why so few IDEs support it.

The good news is that VS Code's Debug Adapter Protocol seems to become a standard for IDEs (like the Language Server Protocol already did). AFAIK Eclipse and Visual Studio are working on supporting this protocol soon and I think that others will follow.
Then I will be able to offer this adapter for these IDEs.

**Comment by digitarald** [comment]
Will be handled in https://github.com/firefox-devtools/vscode-firefox-debug/issues/108
