### ISSUE TITLE
Firefox option "Ask to save logins and passwords for websites" always disabled

### ISSUE THREAD

**Issue by Starli0n** [firefox-devtools/vscode-firefox-debug#308]
Hi,

I do not know if it is a bug or a feature but the following option is always disabled when starting the debugging:
- _Ask to save logins and passwords for websites_

Even though, it is enabled in the original profile, it is systematically disabled.

We can see it in the `about:config` under _signon.rememberSignons_: **False**

It is really annoying and it is a no go to use this extension for me as I have to enter my login/password each time I am debugging my website.
I wanted to switch from Chrome to Firefox Developer Tool, but for now I will not, except if a workaround exists.

**Comment by arshadpakkali** [comment]
hey @Starli0n 
Here is a workaround that I'm using for now 
```
           "request": "launch",
           "reAttach": true,
           "url": "http://localhost:4200/",
           "webRoot": "${workspaceRoot}/",
           "profile":"Debug_user",
           "keepProfileChanges": true
```
Here please note the `profile` and `keepProfileChanges`.

you can either create a new profile just for debugging by going to `about:profiles`  or use the one that's marked as the `default`
the `keepProfileChanges` will make sure the passwords you save wont be erased after quitting
Adding to it You'll need to set the `rememberSignons: false ` once with you're new profile in debug mode and that's it
