### ISSUE TITLE
Couldn't find the Firefox executable

### ISSUE THREAD

**Issue by mbnoimi** [firefox-devtools/vscode-firefox-debug#316]
I'm unable to launch Firefox and always get this error message:

> Couldn't find the Firefox executable

May you please help me to figure out what's wrong?

**launch.json**
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "firefox",
      "request": "launch",
      "reAttach": true,
      "name": "Launch localhost",
      "url": "http://localhost:9000",
      "webRoot": "${workspaceFolder}",
      "firefoxExecutable": "/usr/bin/firefox"
    }
  ]
}
```
I use flatpak version of vscode. I give it a full access to my files but nothing changed (I don't thing this flatpak issue because I can use chrome debugger without any problem)
```ini
$ flatpak info --show-permissions com.visualstudio.code
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;ssh-auth;
devices=all;
features=devel;
filesystems=/home/laptop/.themes;host-etc;home;xdg-config/gtk-3.0;host;xdg-config/kdeglobals:ro;host-os;/usr/share/themes;

[Session Bus Policy]
org.freedesktop.Flatpak=talk
org.freedesktop.Notifications=talk
com.canonical.AppMenu.Registrar=talk
com.canonical.AppMenu.Registrar.*=talk
org.freedesktop.secrets=talk

[System Bus Policy]
org.freedesktop.login1=talk

[Environment]
GTK_THEME=Mint-Y-Dark-Aqua
LD_LIBRARY_PATH=/app/lib
NPM_CONFIG_GLOBALCONFIG=/app/etc/npmrc
ZYPAK_SPAWN_LATEST_ON_REEXEC=0
QT_STYLE_OVERRIDE=Adwaita-dark
````

**Comment by WebMechanic** [comment]
can you launch Firefox from the terminal using just the `firefox` command? 
if not, make sure it's in the $path.

**Comment by mbnoimi** [comment]
> can you launch Firefox from the terminal using just the `firefox` command? 

I can launch it. Any way I use Chrome debugger instead of Firefox debugger as this project is not really community friendly.
