### ISSUE TITLE
npm run build: Module not found: Error: Can't resolve 'original-fs' in '[...]/vscode-firefox-debug/node_modules/adm-zip/util'

### ISSUE THREAD

**Issue by misieck** [firefox-devtools/vscode-firefox-debug#322]
Module not found: Error: Can't resolve 'original-fs' in '/my/path/vscode-firefox-debug/node_modules/adm-zip/util'

I did: 
`npm i --save original-fs`
npm run build succeded.

now i get from: `npm run package`:
` ERROR  filePath.endsWith is not a function`

node --version: v19.6.0
npm --version: 9.4.2

**Comment by Drew-Daniels** [comment]
I got this same error cloning this repository and running the following while in the root folder (using `node 20.5.0`)
```bash
$ npm i
$ npm run build
```

![image](https://github.com/firefox-devtools/vscode-firefox-debug/assets/62859552/abc0d4ff-fc07-4cc5-8852-153a99f00bc9)
