### ISSUE TITLE
VS Code Insiders can't connect to Firefox

### ISSUE THREAD

**Issue by keckelt** [firefox-devtools/vscode-firefox-debug#337]
Hi!

In VS Code Insiders (v1.82.0) my debugging configuration stopped working, as I receive a connection refused error:
![image](https://github.com/firefox-devtools/vscode-firefox-debug/assets/10337788/71fe80fb-5ed1-42ea-a04d-4b0d73d4d765)

The same project still works fine in standard version of VS Code (v1.80.1).

The Debugger for Firefox extension is v2.9.8 for both.
I already tried to use a different port, but that did not change anything (and I would assume it wouldn't work in the standard version of VS Code if it was a port problem).

Full Version Details of VS Code Insiders:
![image](https://github.com/firefox-devtools/vscode-firefox-debug/assets/10337788/ebf6f275-79a2-4a8a-bfbc-7bb28aa43a51)

**Comment by ChrisMSaltire** [comment]
Getting this now on release 1.82.0
![image](https://github.com/firefox-devtools/vscode-firefox-debug/assets/53841214/a8363e80-1ffe-4b90-8ff3-bdc3be175460)

**Comment by vdtoorn** [comment]
I get the same error now in the new update (regular) of vscode..
![image](https://github.com/firefox-devtools/vscode-firefox-debug/assets/320079/93c46243-39e7-4dea-a9c5-4c5825c3e180)

**Comment by DiamondIceNS** [comment]
Duplicated on VS Code 1.82.1 release.

```
Version: 1.82.1 (user setup)
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-08T08:45:05.575Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by DiamondIceNS** [comment]
Seems to be caused by [VS Code 1.82 internally updating the extension host from Node.js 16 to Node.js 18](https://code.visualstudio.com/updates/v1_82#_update-highlights-for-nodejs).

**Comment by crazyjat** [comment]
IPv6 is being prioritized over IPv4 and firefox debugger doesn't seem to work with IPv6. Fix please!

**Comment by hbenl** [comment]
Fixed in version 2.9.10.

**Comment by ChrisMSaltire** [comment]
Thanks so much, hbenl!

**Comment by keckelt** [comment]
Can confirm this works now (VS Code insders 1.83.0, Debugger for Firefox v2.9.10).

Thank you @hbenl !  Closing the issue.
