### ISSUE TITLE
Firefox and Firefox Developer refusing connection from VS Code debugger

### ISSUE THREAD

**Issue by nathan-alvarez0925** [firefox-devtools/vscode-firefox-debug#339]
This issue started after the latest updates in both Firefox (v117) and Firefox Developer (v118 beta). Start debugging in VS Code has connection actively refused. No issues before latest updates.

**Comment by Gabones** [comment]
I'm having the same problem with Firefox (v116) and Firefox Developer (v118)

**Comment by ChrisMSaltire** [comment]
I believe this is the same as #337. I noticed it first just after updating VSCode to 1.82.0.

**Comment by blm768** [comment]
This seems to also be related to #306. As a workaround, adding `"host": "127.0.0.1"` to the entry in `launch.json` seems to fix the issue.

**Comment by crazyjat** [comment]
This started happening to me today when I updated the VS Code 1.82.1. 

I was able to get around the issue for `attach` by adding `host: "127.0.0.1"` as mentioned above, but this does not work for `launch` configurations.

The issues is that VS Code is now prioritizing ipv6, which doesn't work with firefox debugger. No idea how to fix. Please help!

**Comment by kayzzen01** [comment]
The solution I found so far was this command:

`netsh interface portproxy add v6tov4 listenaddress=::1 listenport=6080 connectaddress=127.0.0.1 connectport=6080`

It works, but I'm not able to use breakpoints. I think this might be another problem. If anyone can do it, I'd be happy to know how 😆

**Comment by llgarrido** [comment]
> This seems to also be related to #306. As a workaround, adding `"host": "127.0.0.1"` to the entry in `launch.json` seems to fix the issue.

With this workaround I can see the console messages in VS but the breakpoints still do not work.

**Comment by maxenko** [comment]
This was happening in VSCode insiders for me a while ago, I guess it made it downstream to stable.

**Comment by hbenl** [comment]
Fixed in version 2.9.10.

**Comment by niklasholm** [comment]
I think this can be closed

**Comment by juliandescottes** [comment]
cc @hbenl should be fixed by your recent release, can we close it?

**Comment by janodvarko** [comment]
Done, than you!
