### ISSUE TITLE
Repo Maintenance on Hiatus?

### ISSUE THREAD

**Issue by kolchurinvv** [firefox-devtools/vscode-firefox-debug#340]
From the commits to the master branch I see the last one is from on Jul 21, 2022 [6ad01e3](https://github.com/firefox-devtools/vscode-firefox-debug/commit/6ad01e350323cb7c1d7bf5b2ac655a803f341f80). Which is over a year at this point. Maybe it's time to hand it over to other members of the community who are better equipped to maintain it. If I this issue comes across passive-aggressive, that's not my intention. I would love to offer my help and I am offering it, however I don't feel I'm qualified enough to meaningfully improve the state of things. Firefox debugger has been and hopefully will continue to be my main debugger. It genuinely used to handle and old vue2 + webpack5 project (still in production) debugging much better than chrome ever could. With that I'm hoping that there's some acceptable path forward for everyone: maintainers and users alike.

**Comment by nchevobbe** [comment]
We (the Firefox DevTools team) plan to maintain this repo now. We don't know the codebase yet so it will take some time before we're up to speed, but it's our goal to have it taken care of as we do for the firefox toolbox.
