### ISSUE TITLE
Firefox on launch not opening debug URL

### ISSUE THREAD

**Issue by 0xff8** [firefox-devtools/vscode-firefox-debug#351]
Whenever I start debugging on my MacOS , the Firefox Developer Edition getting launched, but the url defined in the `launch.json` config not opened. So I always have to manually type it in the url field.  Could you suggest me what is wrong?

Here is my launch json:
```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "firefox",
        "request": "launch",
        "name": "client: firefox",
        "url": "http://localhost:3000",
        "reAttach": true,
        "webRoot": "${workspaceFolder}"
      },
      {
        "command": "npm run dev",
        "name": "Run npm dev",
        "request": "launch",
        "type": "node-terminal"
      }
    ]
}
```

**Comment by nchevobbe** [comment]
I'm going to close the issue, but feel free to reopen it if the provided solution doesn't work for you
