### ISSUE TITLE
Can't Debug WebWorker in Firefox from VS Code

### ISSUE THREAD

**Issue by crazyjat** [firefox-devtools/vscode-firefox-debug#354]
I'm trying to debug a WebWorker I am running through Firefox. Set breakpoints in worker file don't get hit. I have searched online and found no help for how to do this.

Example:

**Browser**
```
const worker = new Worker(new URL("./worker", import.meta.url));
worker.onmessage = (e) => {
    console.log(e.data);
};

worker.postMessage("test");
```

**Worker**
```
self.onmessage = (e) => {
    self.postMessage("done");
};
```

**Comment by nchevobbe** [comment]
I just tried to debug a worker and I was able to set a breakpoint and get it to pause fine.
Is your worker running? Can you see it in the threads panel?

**Comment by crazyjat** [comment]
No longer using WebWorkers. Sorry if someone else hits this.
