### ISSUE TITLE
Incorrect handing of profile and profileDir configuration directives on MacOS

### ISSUE THREAD

**Issue by brablc** [firefox-devtools/vscode-firefox-debug#355]
I had big problems to use separate profile with "Firefox Developer Edition", it looks like it ignores or does not handle properly directives `profile` and `profileDir` and uses the profile with the name `default`. With my settings:

```json
    {
      "name": "Firefox Launch",
      "type": "firefox",
      "request": "launch",
      "reAttach": true,
      "keepProfileChanges": true,
      "profile": "default-dev",
```

I can see this in the process list:
```bash
$ pgrep -fl "Firefox Developer"
10838 /Applications/Firefox Developer Edition.app/Contents/MacOS/firefox -start-debugger-server 6000 -no-remote -profile /Users/ondrej/Library/Application Support/Firefox/Profiles/qs0ps7n4.default http://localhost:8000/
```

#### Problem 1 - `profile` directive ignored

It would always go to `profiles.ini` and search `Path` for profile named `default`, if it is not there it would even say so:
```
cannot find profile default
```

#### Problem 2 - `profileDir` cannot be used

When using ONLY `profileDir` and no `profile` directive it failes with:
```
You can set either "profile" or "profileDir", but not both
```
This seems to be related to problem no. 1 some part of extension probably injects Path of the default profile to for `profileDir` and application thinks it was added by the configuration.

#### Problem 3 - `firefoxArgs` cannot be used to overwrite profile settings

Because it is injected among other parameters, instead of adding it at the end:
```json
"firefoxArgs": ["-P"],
```
Would be injected like this:
```bash
... -no-remote -P -profile ...
```
Obviously this does not allow profile manager to be invoked or profile changed.

**Comment by hbenl** [comment]
> some part of extension probably injects Path of the default profile

This sounds like you have `firefox.profile` set in your VSCode settings, which will override the `profile` property in your launch configuration.

**Comment by brablc** [comment]
> > some part of extension probably injects Path of the default profile
> 
> This sounds like you have `firefox.profile` set in your VSCode settings, which will override the `profile` property in your launch configuration.

You are right, I had it in both my user preferences and `.vscode/settings.json`. Now with both of them removed it finally recognizes `profile` directive from `.vscode/launch.json`.

I would expect the last one to take preceedence but will let it to others to decide. It works now. Thank you very much! Let me know if you think it is worth reporting the preceedence problem.
