### ISSUE TITLE
Debugger doesn't work in Firefox developer edition [version 125.0b9]

### ISSUE THREAD

**Issue by Abdelhafid01** [firefox-devtools/vscode-firefox-debug#361]
I have approximately the same issue with the debugger in firefox developer edition (version 125.0b9) doesn't have effect, it doesn't work at all. so I swith to firefox normal edition (version 124.0.2) it works partially and I don't know why it is stopped and have the issue in debug console which tells me:
SyntaxError: import.meta may only appear in a module

NG0912: Component ID generation collision detected. Components 'NavbarItemMenusComponent' and 'NavbarItemMenusComponent' with selector 'bl-navbar-item-menus' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912
core.mjs:2149
[KEYCLOAK] Instantiation using the Keycloak function has been deprecated and support will be removed in future versions. Use the new operator to create an instance instead.
keycloak.mjs:30

TypeError: au.shift is not a function

here my launch.json config:
{
"version": "0.2.0",
"configurations": [
{
"type": "firefox",
"request": "launch",
"name": "Launch firefox",
"reAttach": false,
"url": "http://localhost:4999",
"webRoot": "${workspaceFolder}",
"firefoxExecutable": "C:\Program Files\Mozilla Firefox\firefox.exe",
"profileDir": "C:\Users\Abdelhafid.CHETOUANI\AppData\Roaming\Mozilla\Firefox\Profiles\p0g2jmlu.default",
"firefoxArgs": ["-private", "-purgecaches"]
},
{
"type": "chrome",
"request": "launch",
"name": "Launch Chrome against localhost",
"url": "http://localhost:4999",
"webRoot": "${workspaceFolder}"
}
]
}

And with Chrome and Edge the debugger works nicely.

**Comment by sfreeman-f5** [comment]
I also am not having any luck on MacOS with the same dev version of FF. It doesn't work at all.

**Comment by zeorin** [comment]
Same here:
```
DEBUG|000.038|FirefoxDebugAdapter: 0 threads
DEBUG|002.236|DebugConnection: Received response/event {"from":"root","applicationType":"browser","testConnectionPrefix":"server1.conn14.","traits":{"networkMonitor":true,"resources":{"extensions-backgroundscript-status":true},"workerConsoleApiMessagesDispatchedToMainThread":true}}
DEBUG|002.237|RootActorProxy: Fetching root
DEBUG|002.237|DebugConnection: Sending request {"to":"root","type":"getRoot"}
DEBUG|002.237|DebugConnection: Received response/event {"preferenceActor":"server1.conn14.preferenceActor1","addonsActor":"server1.conn14.addonsActor2","deviceActor":"server1.conn14.deviceActor3","heapSnapshotFileActor":"server1.conn14.heapSnapshotFileActor4","perfActor":"server1.conn14.perfActor5","parentAccessibilityActor":"server1.conn14.parentAccessibilityActor6","screenshotActor":"server1.conn14.screenshotActor7","from":"root"}
DEBUG|002.237|RootActorProxy: Received root response
DEBUG|002.238|RootActorProxy: Fetching tabs
DEBUG|002.238|DebugConnection: Sending request {"to":"root","type":"listTabs"}
DEBUG|002.280|DebugConnection: Received response/event {"from":"root","error":"ReferenceError","message":"TabDescriptorActor is not defined","fileName":"resource://devtools/server/actors/webbrowser.js","lineNumber":322,"columnNumber":3}
WARN |002.280|RootActorProxy: Unknown message from RootActor: {"from":"root","error":"ReferenceError","message":"TabDescriptorActor is not defined","fileName":"resource://devtools/server/actors/webbrowser.js","lineNumber":322,"columnNumber":3}
```
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Attach Firefox",
			"type": "firefox",
			"request": "attach",
			"url": "http://localhost:3000",
			"suggestPathMappingWizard": true,
			"webRoot":"${workspaceFolder}",
			"log": {
				"fileName": "${workspaceFolder}/vscode-firefox-debug.log",
				"fileLevel": {
					"default": "Debug"
				}
			}
		}
	]
}
```
```
125.0b3 (64-bit)
Mozilla Firefox Developer Edition for NixOS
NixOS 23.11 (Tapir)
firefox-devedition from nixpkgs commit 1042fd8b148a9105f3c0aca3a6177fd1d9360ba5
```

**Comment by MasterAzazel** [comment]
its not working for me either plugin version 2.9.10 with firefox developer edition 126.0b9 and this launch config
takes forever to open then shows a white tab and gives me all kinds of exceptions but cant load the page

works fine without the debugger, or with debugger and chrome

`{
      "type": "firefox",
      "request": "launch",
      // "reAttach": true,
      "name": "Launch FF",
      "url": "http://localhost:8100",
      "webRoot": "${workspaceFolder}",
}`

**Comment by sfreeman-f5** [comment]
This seems to be resolved, it works for me now:

```
DEBUG|000.049|DebugConnection: Sending request {"to":"root","type":"listTabs"}
DEBUG|000.050|FirefoxDebugAdapter: Setting exception filters: []
DEBUG|000.051|DebugConnection: Received response/event {"tabs":[{"actor":"server1.conn3.tabDescriptor8","browserId":3,"browsingContextID":4,"isZombieTab":false,"outerWindowID":8,"selected":true,"title":"Panorama","traits":{"watcher":true,"supportsReloadDescriptor":true},"url":"http://localhost:5173/"}],"from":"root"}
DEBUG|000.051|RootActorProxy: Received 1 tabs
DEBUG|000.051|RootActorProxy: Tab server1.conn3.tabDescriptor8 opened
DEBUG|000.051|TabDescriptorActorProxy: Connecting to tab
``` 

- VS Code 'Debugger for firefox v2.9.10
- Firefox Developer Edition version: 127.0b6 (64-bit)
