### ISSUE TITLE
Instructions or support for create-react-app

### ISSUE THREAD

**Issue by synchronos-t** [firefox-devtools/vscode-firefox-debug#78]
A suggestion: As **create-react-app** is quite popular nowadays, I think, perhaps there should be out-of-the-box support or at least a segment in the instructions how to correctly configure the debugger for it.

The only issue is with the directory mapping. Create-react-app by default maps the sources by adding the absolute path to it. E.g., if I have a project _C:\webstuff\my-react-app_, the created _App.js_ would be at a path `C:\webstuff\my-react-app\src\App.js`. Now, in the browser, the source mappings point to a path `http://localhost:3000/static/js/C:/webstuff/my-react-app/src/App.js`.

For that to start working, I need to add a path mapping:

`"pathMappings": [{
  "url": "http://localhost:3000/static/js/C:/webstuff/my-react-app",
  "path": "C:/webstuff/my-react-app"
}]`

Also, as I use the VSCode from the _src_ directory, not the app root, I had to change the `webRoot` to an absolute path pointing to the directory above the _src_. Not a big issue, but perhaps a reminder in the instructions would be nice that the `$workspaceFolder` only works if set to the project root, not the _src_ root.

**Comment by hbenl** [comment]
Since #102 is fixed, create-react-app works out-of-the-box. There's no need to add `pathMappings` or change `webRoot` anymore.
