### ISSUE TITLE
Use real Firefox icon

### ISSUE THREAD

**Issue by rugk** [firefox-devtools/vscode-firefox-debug#81]
As the Chrome/ium debugger also uses the official icon, I guess it would look nicer, if you use the official Firefox logo, too: https://design.firefox.com/photon/visuals/product-identity-assets.html

**Comment by hbenl** [comment]
Last time I checked their legalese sounded like they did not allow the Firefox logo to be used for any other software product.
I'm sure that's just a precaution and they wouldn't actually mind if I used the logo for this adapter, but I feel I should ask them first (which I intend to do soon).

**Comment by rugk** [comment]
Well [at the bottom of that page](https://design.firefox.com/photon/visuals/product-identity-assets.html#additional-guidelines) some guidelines are listed and AFAIK you would satisfy them. Generally, I guess, it would fall under fair use, but it's better to ask, for sure. :smile:

**Comment by digitarald** [comment]
@hbenl let me check on the Mozilla side and find out for you.

**Comment by fvsch** [comment]
Indeed that extension would be easier to spot in [the list of Debugger extensions](https://marketplace.visualstudio.com/search?target=VSCode&category=Debuggers&sortBy=Downloads) if it could use the Firefox logo. I had a hard time spotting it in the 19th position.

Maybe it could be argued that this extension is called "... for Firefox" and not "Firefox", is not a web browser, and is not targetted at a general audience?

Some add-ons distributed on AMO already use a modified Firefox logo or something clearly inspired by it:
https://addons.mozilla.org/en-US/firefox/addon/foxtana-pro-redirect-cortana/
https://addons.mozilla.org/en-US/firefox/addon/foxfilter/
(Found a few others but with <100 users.)

**Comment by digitarald** [comment]
Holger and I are working out the details here and will keep this thread posted.

**Comment by digitarald** [comment]
Landed in 218df98dc3e79b60b6615980b101911f55059921
